export const wordData = {
    "verbs": [
        {"kanji":"<ruby>行<rt>い<\/rt><\/ruby>く","type":"irv","eng":"go", "group": "iku"},
        {"kanji":"する","type":"irv","eng":"do, make", "group": "suru"},
        {"kanji":"<ruby>来<rt>く<\/rt><\/ruby>る","type":"irv","eng":"come"},
        {"kanji":"ある","type":"irv","eng":"have, exists, is (inanimate)"},
        {"kanji":"<ruby>問<rt>と<\/rt><\/ruby>う","type":"irv","eng":"ask, accuse"},
        {"kanji":"いる","type":"ru","eng":"exists, is (living things)"},
        {"kanji":"<ruby>始<rt>はじ<\/rt><\/ruby>める","type":"ru","eng":"begin"},
        {"kanji":"<ruby>借<rt>か<\/rt><\/ruby>りる","type":"ru","eng":"borrow, rent"},
        {"kanji":"<ruby>続<rt>つづ<\/rt><\/ruby>ける","type":"ru","eng":"continue, proceed"},
        {"kanji":"<ruby>決<rt>き<\/rt><\/ruby>める","type":"ru","eng":"decide, choose"},
        {"kanji":"<ruby>食<rt>た<\/rt><\/ruby>べる","type":"ru","eng":"eat"},
        {"kanji":"<ruby>忘<rt>わす<\/rt><\/ruby>れる","type":"ru","eng":"forget"},
        {"kanji":"<ruby>降<rt>お<\/rt><\/ruby>りる","type":"ru","eng":"get off, go down"},
        {"kanji":"<ruby>疲<rt>つか<\/rt><\/ruby>れる","type":"ru","eng":"get tired"},
        {"kanji":"<ruby>起<rt>お<\/rt><\/ruby>きる","type":"ru","eng":"get up, wake up"},
        {"kanji":"あげる","type":"ru","eng":"give"},
        {"kanji":"<ruby>出<rt>で<\/rt><\/ruby>る","type":"ru","eng":"leave, exit, appear"},
        {"kanji":"<ruby>助<rt>たす<\/rt><\/ruby>ける","type":"ru","eng":"help"},
        {"kanji":"<ruby>見<rt>み<\/rt><\/ruby>る","type":"ru","eng":"see, look"},
        {"kanji":"<ruby>開<rt>あ<\/rt><\/ruby>ける","type":"ru","eng":"open"},
        {"kanji":"<ruby>覚<rt>おぼ<\/rt><\/ruby>える","type":"ru","eng":"remember, learn"},
        {"kanji":"<ruby>寝<rt>ね<\/rt><\/ruby>る","type":"ru","eng":"sleep, go to bed"},
        {"kanji":"<ruby>閉<rt>し<\/rt><\/ruby>める","type":"ru","eng":"close"},
        {"kanji":"<ruby>着<rt>き<\/rt><\/ruby>る","type":"ru","eng":"put on, wear (shirt, jacket, etc)"},
        {"kanji":"なる","type":"u","eng":"become"},
        {"kanji":"<ruby>乗<rt>の<\/rt><\/ruby>る","type":"u","eng":"board, ride"},
        {"kanji":"<ruby>切<rt>き<\/rt><\/ruby>る","type":"u","eng":"cut"},
        {"kanji":"やる","type":"u","eng":"do, give"},
        {"kanji":"<ruby>終<rt>お<\/rt><\/ruby>わる","type":"u","eng":"end"},
        {"kanji":"<ruby>上<rt>あ<\/rt><\/ruby>がる","type":"u","eng":"go up, rise","altOkurigana":["上る"]},
        {"kanji":"<ruby>知<rt>し<\/rt><\/ruby>る","type":"u","eng":"know"},
        {"kanji":"<ruby>作<rt>つく<\/rt><\/ruby>る","type":"u","eng":"make, build"},
        {"kanji":"<ruby>帰<rt>かえ<\/rt><\/ruby>る","type":"u","eng":"return, go home"},
        {"kanji":"<ruby>取<rt>と<\/rt><\/ruby>る","type":"u","eng":"take, steal"},
        {"kanji":"<ruby>買<rt>か<\/rt><\/ruby>う","type":"u","eng":"buy"},
        {"kanji":"<ruby>笑<rt>わら<\/rt><\/ruby>う","type":"u","eng":"laugh, smile"},
        {"kanji":"<ruby>会<rt>あ<\/rt><\/ruby>う","type":"u","eng":"meet"},
        {"kanji":"<ruby>言<rt>い<\/rt><\/ruby>う","type":"u","eng":"say, utter"},
        {"kanji":"<ruby>思<rt>おも<\/rt><\/ruby>う","type":"u","eng":"think, believe"},
        {"kanji":"<ruby>使<rt>つか<\/rt><\/ruby>う","type":"u","eng":"use"},
        {"kanji":"<ruby>持<rt>も<\/rt><\/ruby>つ","type":"u","eng":"hold, have"},
        {"kanji":"<ruby>待<rt>ま<\/rt><\/ruby>つ","type":"u","eng":"wait"},
        {"kanji":"<ruby>立<rt>た<\/rt><\/ruby>つ","type":"u","eng":"stand up"},
        {"kanji":"<ruby>聞<rt>き<\/rt><\/ruby>く","type":"u","eng":"hear, listen"},
        {"kanji":"<ruby>引<rt>ひ<\/rt><\/ruby>く","type":"u","eng":"pull, tug"},
        {"kanji":"<ruby>履<rt>は<\/rt><\/ruby>く","type":"u","eng":"put on, wear (pants, skirt, shoes, etc)"},
        {"kanji":"<ruby>歩<rt>ある<\/rt><\/ruby>く","type":"u","eng":"walk"},
        {"kanji":"<ruby>書<rt>か<\/rt><\/ruby>く","type":"u","eng":"write"},
        {"kanji":"<ruby>働<rt>はたら<\/rt><\/ruby>く","type":"u","eng":"work"},
        {"kanji":"<ruby>死<rt>し<\/rt><\/ruby>ぬ","type":"u","eng":"die, pass away"},
        {"kanji":"<ruby>飲<rt>の<\/rt><\/ruby>む","type":"u","eng":"drink"},
        {"kanji":"<ruby>楽<rt>たの<\/rt><\/ruby>しむ","type":"u","eng":"enjoy, have fun"},
        {"kanji":"<ruby>進<rt>すす<\/rt><\/ruby>む","type":"u","eng":"advance, go forward"},
        {"kanji":"<ruby>住<rt>す<\/rt><\/ruby>む","type":"u","eng":"live, inhabit"},
        {"kanji":"<ruby>読<rt>よ<\/rt><\/ruby>む","type":"u","eng":"read"},
        {"kanji":"<ruby>休<rt>やす<\/rt><\/ruby>む","type":"u","eng":"rest, be absent"},
        {"kanji":"<ruby>遊<rt>あそ<\/rt><\/ruby>ぶ","type":"u","eng":"play, have a good time"},
        {"kanji":"<ruby>学<rt>まな<\/rt><\/ruby>ぶ","type":"u","eng":"study, learn"},
        {"kanji":"<ruby>選<rt>えら<\/rt><\/ruby>ぶ","type":"u","eng":"choose, select"},
        {"kanji":"<ruby>返<rt>かえ<\/rt><\/ruby>す","type":"u","eng":"return (something), put back"},
        {"kanji":"<ruby>押<rt>お<\/rt><\/ruby>す","type":"u","eng":"push, press"},
        {"kanji":"<ruby>治<rt>なお<\/rt><\/ruby>す","type":"u","eng":"cure, repair"},
        {"kanji":"<ruby>話<rt>はな<\/rt><\/ruby>す","type":"u","eng":"talk, speak"},
        {"kanji":"<ruby>探<rt>さが<\/rt><\/ruby>す","type":"u","eng":"search, look for"},
        {"kanji":"<ruby>貸<rt>か<\/rt><\/ruby>す","type":"u","eng":"lend, loan"},
        {"kanji":"<ruby>泳<rt>およ<\/rt><\/ruby>ぐ","type":"u","eng":"swim"},
        {"kanji":"<ruby>脱<rt>ぬ<\/rt><\/ruby>ぐ","type":"u","eng":"take off clothes, undress"},
        {"kanji":"<ruby>急<rt>いそ<\/rt><\/ruby>ぐ","type":"u","eng":"hurry"},
        {"kanji":"<ruby>稼<rt>かせ<\/rt><\/ruby>ぐ","type":"u","eng":"earn income, make money"},
        {"kanji":"<ruby>寛<rt>くつろ<\/rt><\/ruby>ぐ","type":"u","eng":"relax, feel at home"},
        {"kanji":"<ruby>繋<rt>つな<\/rt><\/ruby>ぐ","type":"u","eng":"connect, link together"},
        {"kanji":"<ruby>分<rt>わ<\/rt><\/ruby>かる","type":"u","eng":"understand"},
        {"kanji":"<ruby>勉<rt>べん<\/rt><\/ruby><ruby>強<rt>きょう<\/rt><\/ruby>する","type":"irv","eng":"study", "group": "suru"},
        {"kanji":"<ruby>受<rt>う<\/rt><\/ruby>け<ruby>持<rt>も<\/rt><\/ruby>つ","type":"u","eng":"take charge of"},
        {"kanji":"<ruby>持<rt>も<\/rt><\/ruby>って<ruby>行<rt>い<\/rt><\/ruby>く","type":"irv","eng":"take, carry away", "group": "iku"},
        {"kanji":"<ruby>食<rt>た<\/rt><\/ruby>べ<ruby>歩<rt>ある<\/rt><\/ruby>く","type":"u","eng":"try food at various restaurants"},
        {"kanji":"<ruby>洗<rt>あら<\/rt><\/ruby>う","type":"u","eng":"wash"},
        {"kanji":"<ruby>受<rt>う<\/rt><\/ruby>ける","type":"ru","eng":"receive, take (an exam)"},
        {"kanji":"<ruby>動<rt>うご<\/rt><\/ruby>く","type":"u","eng":"move"},
        {"kanji":"<ruby>歌<rt>うた<\/rt><\/ruby>う","type":"u","eng":"sing"},
        {"kanji":"<ruby>写<rt>うつ<\/rt><\/ruby>す","type":"u","eng":"copy, photograph"},
        {"kanji":"<ruby>映<rt>うつ<\/rt><\/ruby>る","type":"u","eng":"be reflected"},
        {"kanji":"<ruby>選<rt>えら<\/rt><\/ruby>ぶ","type":"u","eng":"choose"},
        {"kanji":"<ruby>送<rt>おく<\/rt><\/ruby>る","type":"u","eng":"send"},
        {"kanji":"<ruby>置<rt>お<\/rt><\/ruby>く","type":"u","eng":"put, place"},
        {"kanji":"<ruby>遅<rt>おく<\/rt><\/ruby>れる","type":"ru","eng":"be late"},
        {"kanji":"<ruby>起<rt>お<\/rt><\/ruby>こす","type":"u","eng":"wake someone up"},
        {"kanji":"<ruby>行<rt>おこな<\/rt><\/ruby>う","type":"u","eng":"perform, conduct"},
        {"kanji":"<ruby>怒<rt>おこ<\/rt><\/ruby>る","type":"u","eng":"get angry"},
        {"kanji":"<ruby>教<rt>おし<\/rt><\/ruby>える","type":"ru","eng":"teach, inform"},
        {"kanji":"<ruby>落<rt>お<\/rt><\/ruby>とす","type":"u","eng":"drop"},
        {"kanji":"<ruby>落<rt>お<\/rt><\/ruby>ちる","type":"ru","eng":"fall"},
        {"kanji":"<ruby>踊<rt>おど<\/rt><\/ruby>る","type":"u","eng":"dance"},
        {"kanji":"<ruby>驚<rt>おどろ<\/rt><\/ruby>く","type":"u","eng":"be surprised"},
        {"kanji":"<ruby>思<rt>おも<\/rt><\/ruby>い<ruby>出<rt>だ<\/rt><\/ruby>す","type":"u","eng":"recall, remember"},
        {"kanji":"<ruby>折<rt>お<\/rt><\/ruby>る","type":"u","eng":"break, fold"},
        {"kanji":"<ruby>下<rt>お<\/rt><\/ruby>りる","type":"ru","eng":"descend"},
        {"kanji":"<ruby>替<rt>か<\/rt><\/ruby>える","type":"ru","eng":"exchange, replace"},
        {"kanji":"<ruby>掛<rt>か<\/rt><\/ruby>ける","type":"ru","eng":"hang, sit, call"},
        {"kanji":"<ruby>飾<rt>かざ<\/rt><\/ruby>る","type":"u","eng":"decorate"},
        {"kanji":"<ruby>勝<rt>か<\/rt><\/ruby>つ","type":"u","eng":"win"},
        {"kanji":"<ruby>片付<rt>かたづ<\/rt><\/ruby>ける","type":"ru","eng":"tidy up"},
        {"kanji":"<ruby>通<rt>かよ<\/rt><\/ruby>う","type":"u","eng":"commute"},
        {"kanji":"<ruby>乾<rt>かわ<\/rt><\/ruby>く","type":"u","eng":"dry (intransitive)"},
        {"kanji":"<ruby>乾<rt>かわ<\/rt><\/ruby>かす","type":"u","eng":"dry (transitive)"},
        {"kanji":"<ruby>考<rt>かんが<\/rt><\/ruby>える","type":"ru","eng":"think, consider"},
        {"kanji":"<ruby>感<rt>かん<\/rt><\/ruby>じる","type":"ru","eng":"feel"},
        {"kanji":"<ruby>頑<rt>がん<\/rt><\/ruby><ruby>張<rt>ば<\/rt><\/ruby>る","type":"u","eng":"do one's best"},
        {"kanji":"<ruby>消<rt>き<\/rt><\/ruby>える","type":"ru","eng":"go out, vanish"},
        {"kanji":"<ruby>聞<rt>き<\/rt><\/ruby>こえる","type":"ru","eng":"be audible"},
        {"kanji":"<ruby>決<rt>き<\/rt><\/ruby>まる","type":"u","eng":"be decided"},
        {"kanji":"<ruby>決<rt>き<\/rt><\/ruby>める","type":"ru","eng":"decide"},
        {"kanji":"<ruby>消<rt>け<\/rt><\/ruby>す","type":"u","eng":"erase, turn off"},
        {"kanji":"<ruby>答<rt>こた<\/rt><\/ruby>える","type":"ru","eng":"answer"},
        {"kanji":"<ruby>困<rt>こま<\/rt><\/ruby>る","type":"u","eng":"be in trouble"},
        {"kanji":"<ruby>壊<rt>こわ<\/rt><\/ruby>す","type":"u","eng":"break (transitive)"},
        {"kanji":"<ruby>壊<rt>こわ<\/rt><\/ruby>れる","type":"ru","eng":"break (intransitive)"},
        {"kanji":"<ruby>探<rt>さが<\/rt><\/ruby>す","type":"u","eng":"search for"},
        {"kanji":"<ruby>下<rt>さ<\/rt><\/ruby>がる","type":"u","eng":"go down"},
        {"kanji":"<ruby>下<rt>さ<\/rt><\/ruby>げる","type":"ru","eng":"lower"},
        {"kanji":"<ruby>差<rt>さ<\/rt><\/ruby>す","type":"u","eng":"point, hold (umbrella)"},
        {"kanji":"<ruby>騒<rt>さわ<\/rt><\/ruby>ぐ","type":"u","eng":"make noise"},
        {"kanji":"<ruby>触<rt>さわ<\/rt><\/ruby>る","type":"u","eng":"touch"},
        {"kanji":"<ruby>叱<rt>しか<\/rt><\/ruby>る","type":"u","eng":"scold"},
        {"kanji":"<ruby>信<rt>しん<\/rt><\/ruby>じる","type":"ru","eng":"believe"},
        {"kanji":"<ruby>閉<rt>し<\/rt><\/ruby>まる","type":"u","eng":"close (intransitive)"},
        {"kanji":"<ruby>知<rt>し<\/rt><\/ruby>らせる","type":"ru","eng":"notify"},
        {"kanji":"<ruby>調<rt>しら<\/rt><\/ruby>べる","type":"ru","eng":"investigate, look up"},
        {"kanji":"<ruby>過<rt>す<\/rt><\/ruby>ぎる","type":"ru","eng":"pass, exceed"},
        {"kanji":"<ruby>空<rt>す<\/rt><\/ruby>く","type":"u","eng":"become empty, hungry"},
        {"kanji":"<ruby>進<rt>すす<\/rt><\/ruby>める","type":"ru","eng":"advance, promote"},
        {"kanji":"<ruby>捨<rt>す<\/rt><\/ruby>てる","type":"ru","eng":"throw away"},
        {"kanji":"<ruby>滑<rt>すべ<\/rt><\/ruby>る","type":"u","eng":"slip"},
        {"kanji":"<ruby>済<rt>す<\/rt><\/ruby>む","type":"u","eng":"finish, conclude"},
        {"kanji":"<ruby>座<rt>すわ<\/rt><\/ruby>る","type":"u","eng":"sit"},
        {"kanji":"<ruby>育<rt>そだ<\/rt><\/ruby>てる","type":"ru","eng":"raise, rear"},
        {"kanji":"<ruby>倒<rt>たお<\/rt><\/ruby>れる","type":"ru","eng":"fall over"},
        {"kanji":"<ruby>助<rt>たす<\/rt><\/ruby>かる","type":"u","eng":"be saved"},
        {"kanji":"<ruby>訪<rt>たず<\/rt><\/ruby>ねる","type":"ru","eng":"visit"},
        {"kanji":"<ruby>尋<rt>たず<\/rt><\/ruby>ねる","type":"ru","eng":"ask, inquire"},
        {"kanji":"<ruby>建<rt>た<\/rt><\/ruby>てる","type":"ru","eng":"build"},
        {"kanji":"<ruby>頼<rt>たの<\/rt><\/ruby>む","type":"u","eng":"request, ask"},
        {"kanji":"<ruby>足<rt>た<\/rt><\/ruby>りる","type":"ru","eng":"be sufficient"},
        {"kanji":"<ruby>捕<rt>つか<\/rt><\/ruby>まえる","type":"ru","eng":"catch, arrest"},
        {"kanji":"<ruby>疲<rt>つか<\/rt><\/ruby>れる","type":"ru","eng":"get tired"},
        {"kanji":"<ruby>着<rt>つ<\/rt><\/ruby>く","type":"u","eng":"arrive"},
        {"kanji":"<ruby>付<rt>つ<\/rt><\/ruby>ける","type":"ru","eng":"attach, turn on"},
        {"kanji":"<ruby>伝<rt>つた<\/rt><\/ruby>える","type":"ru","eng":"convey"},
        {"kanji":"<ruby>続<rt>つづ<\/rt><\/ruby>く","type":"u","eng":"continue (intransitive)"},
        {"kanji":"<ruby>包<rt>つつ<\/rt><\/ruby>む","type":"u","eng":"wrap"},
        {"kanji":"<ruby>連<rt>つ<\/rt><\/ruby>れる","type":"ru","eng":"lead, take along"},
        {"kanji":"<ruby>手伝<rt>てつだ<\/rt><\/ruby>う","type":"u","eng":"help"},
        {"kanji":"<ruby>通<rt>とお<\/rt><\/ruby>る","type":"u","eng":"pass through"},
        {"kanji":"<ruby>届<rt>とど<\/rt><\/ruby>ける","type":"ru","eng":"deliver"},
        {"kanji":"<ruby>止<rt>と<\/rt><\/ruby>まる","type":"u","eng":"stop"},
        {"kanji":"<ruby>泊<rt>と<\/rt><\/ruby>まる","type":"u","eng":"stay overnight"},
        {"kanji":"<ruby>止<rt>と<\/rt><\/ruby>める","type":"ru","eng":"stop, park"},
        {"kanji":"<ruby>取<rt>と<\/rt><\/ruby>り<ruby>替<rt>か<\/rt><\/ruby>える","type":"ru","eng":"exchange"},
        {"kanji":"<ruby>取<rt>と<\/rt><\/ruby>る","type":"u","eng":"take, handle"},
        {"kanji":"<ruby>直<rt>なお<\/rt><\/ruby>る","type":"u","eng":"be repaired"},
        {"kanji":"<ruby>治<rt>なお<\/rt><\/ruby>る","type":"u","eng":"be cured"},
        {"kanji":"<ruby>泣<rt>な<\/rt><\/ruby>く","type":"u","eng":"cry"},
        {"kanji":"<ruby>亡<rt>な<\/rt><\/ruby>くなる","type":"u","eng":"die, pass away"},
        {"kanji":"<ruby>無<rt>な<\/rt><\/ruby>くなる","type":"u","eng":"be lost, run out"},
        {"kanji":"<ruby>投<rt>な<\/rt><\/ruby>げる","type":"ru","eng":"throw"},
        {"kanji":"<ruby>鳴<rt>な<\/rt><\/ruby>る","type":"u","eng":"ring, sound"},
        {"kanji":"<ruby>並<rt>なら<\/rt><\/ruby>ぶ","type":"u","eng":"line up (intransitive)"},
        {"kanji":"<ruby>並<rt>なら<\/rt><\/ruby>べる","type":"ru","eng":"line up (transitive)"},
        {"kanji":"<ruby>慣<rt>な<\/rt><\/ruby>れる","type":"ru","eng":"get used to"},
        {"kanji":"<ruby>逃<rt>に<\/rt><\/ruby>げる","type":"ru","eng":"escape"},
        {"kanji":"<ruby>似<rt>に<\/rt><\/ruby>る","type":"ru","eng":"resemble"},
        {"kanji":"<ruby>脱<rt>ぬ<\/rt><\/ruby>ぐ","type":"u","eng":"take off (clothes)"},
        {"kanji":"<ruby>盗<rt>ぬす<\/rt><\/ruby>む","type":"u","eng":"steal"},
        {"kanji":"<ruby>塗<rt>ぬ<\/rt><\/ruby>る","type":"u","eng":"paint, spread"},
        {"kanji":"<ruby>濡<rt>ぬ<\/rt><\/ruby>れる","type":"ru","eng":"get wet"},
        {"kanji":"<ruby>願<rt>ねが<\/rt><\/ruby>う","type":"u","eng":"wish, request"},
        {"kanji":"<ruby>眠<rt>ねむ<\/rt><\/ruby>る","type":"u","eng":"sleep"},
        {"kanji":"<ruby>登<rt>のぼ<\/rt><\/ruby>る","type":"u","eng":"climb"},
        {"kanji":"<ruby>乗<rt>の<\/rt><\/ruby>り<ruby>換<rt>か<\/rt><\/ruby>える","type":"ru","eng":"transfer (trains)"},
        {"kanji":"<ruby>運<rt>はこ<\/rt><\/ruby>ぶ","type":"u","eng":"carry"},
        {"kanji":"<ruby>始<rt>はじ<\/rt><\/ruby>まる","type":"u","eng":"begin (intransitive)"},
        {"kanji":"<ruby>外<rt>はず<\/rt><\/ruby>す","type":"u","eng":"remove, unfasten"},
        {"kanji":"<ruby>払<rt>はら<\/rt><\/ruby>う","type":"u","eng":"pay"},
        {"kanji":"<ruby>晴<rt>は<\/rt><\/ruby>れる","type":"ru","eng":"clear up (weather)"},
        {"kanji":"<ruby>光<rt>ひか<\/rt><\/ruby>る","type":"u","eng":"shine"},
        {"kanji":"<ruby>引<rt>ひ<\/rt><\/ruby>き<ruby>出<rt>だ<\/rt><\/ruby>す","type":"u","eng":"withdraw"},
        {"kanji":"<ruby>冷<rt>ひ<\/rt><\/ruby>やす","type":"u","eng":"cool down"},
        {"kanji":"<ruby>拾<rt>ひろ<\/rt><\/ruby>う","type":"u","eng":"pick up"},
        {"kanji":"<ruby>増<rt>ふ<\/rt><\/ruby>える","type":"ru","eng":"increase"},
        {"kanji":"<ruby>吹<rt>ふ<\/rt><\/ruby>く","type":"u","eng":"blow"},
        {"kanji":"<ruby>太<rt>ふと<\/rt><\/ruby>る","type":"u","eng":"gain weight"},
        {"kanji":"<ruby>踏<rt>ふ<\/rt><\/ruby>む","type":"u","eng":"step on"},
        {"kanji":"<ruby>振<rt>ふ<\/rt><\/ruby>る","type":"u","eng":"wave, shake"},
        {"kanji":"<ruby>降<rt>ふ<\/rt><\/ruby>る","type":"u","eng":"fall (rain, snow)"},
        {"kanji":"<ruby>減<rt>へ<\/rt><\/ruby>る","type":"u","eng":"decrease"},
        {"kanji":"<ruby>褒<rt>ほ<\/rt><\/ruby>める","type":"ru","eng":"praise"},
        {"kanji":"<ruby>参<rt>まい<\/rt><\/ruby>る","type":"u","eng":"go, come (humble)"},
        {"kanji":"<ruby>負<rt>ま<\/rt><\/ruby>ける","type":"ru","eng":"lose"},
        {"kanji":"<ruby>混<rt>ま<\/rt><\/ruby>ぜる","type":"ru","eng":"mix"},
        {"kanji":"<ruby>間違<rt>まちが<\/rt><\/ruby>える","type":"ru","eng":"make a mistake"},
        {"kanji":"<ruby>守<rt>まも<\/rt><\/ruby>る","type":"u","eng":"protect, obey"},
        {"kanji":"<ruby>回<rt>まわ<\/rt><\/ruby>る","type":"u","eng":"rotate, turn"},
        {"kanji":"<ruby>見<rt>み<\/rt><\/ruby>つかる","type":"u","eng":"be found"},
        {"kanji":"<ruby>見<rt>み<\/rt><\/ruby>つける","type":"ru","eng":"find"},
        {"kanji":"<ruby>向<rt>む<\/rt><\/ruby>かう","type":"u","eng":"face, head toward"},
        {"kanji":"<ruby>迎<rt>むか<\/rt><\/ruby>える","type":"ru","eng":"welcome, meet"},
        {"kanji":"<ruby>召<rt>め<\/rt><\/ruby>し<ruby>上<rt>あ<\/rt><\/ruby>がる","type":"ru","eng":"eat, drink (respectful)"},
        {"kanji":"<ruby>申<rt>もう<\/rt><\/ruby>す","type":"u","eng":"say (humble)"},
        {"kanji":"<ruby>戻<rt>もど<\/rt><\/ruby>る","type":"u","eng":"return"},
        {"kanji":"<ruby>貰<rt>もら<\/rt><\/ruby>う","type":"u","eng":"receive"},
        {"kanji":"<ruby>焼<rt>や<\/rt><\/ruby>く","type":"u","eng":"bake, grill"},
        {"kanji":"<ruby>痩<rt>や<\/rt><\/ruby>せる","type":"ru","eng":"lose weight"},
        {"kanji":"<ruby>休<rt>やす<\/rt><\/ruby>める","type":"ru","eng":"rest (transitive)"},
        {"kanji":"<ruby>止<rt>や<\/rt><\/ruby>める","type":"ru","eng":"stop, quit"},
        {"kanji":"<ruby>汚<rt>よご<\/rt><\/ruby>れる","type":"ru","eng":"get dirty"},
        {"kanji":"<ruby>呼<rt>よ<\/rt><\/ruby>ぶ","type":"u","eng":"call"},
        {"kanji":"<ruby>寄<rt>よ<\/rt><\/ruby>る","type":"u","eng":"stop by"},
        {"kanji":"<ruby>喜<rt>よろこ<\/rt><\/ruby>ぶ","type":"u","eng":"be glad"},
        {"kanji":"<ruby>沸<rt>わ<\/rt><\/ruby>かす","type":"u","eng":"boil (water)"},
        {"kanji":"<ruby>分<rt>わ<\/rt><\/ruby>かれる","type":"ru","eng":"separate, split"},
        {"kanji":"<ruby>沸<rt>わ<\/rt><\/ruby>く","type":"u","eng":"boil (intransitive)"},
        {"kanji":"<ruby>渡<rt>わた<\/rt><\/ruby>す","type":"u","eng":"hand over"},
        {"kanji":"<ruby>渡<rt>わた<\/rt><\/ruby>る","type":"u","eng":"cross (bridge, street)"},
        {"kanji":"<ruby>割<rt>わ<\/rt><\/ruby>る","type":"u","eng":"divide, break"},
        {"kanji":"<ruby>打<rt>う<\/rt><\/ruby>つ","type":"u","eng":"hit, strike"},
        {"kanji":"<ruby>折<rt>お<\/rt><\/ruby>れる","type":"ru","eng":"be broken"},
        {"kanji":"<ruby>伺<rt>うかが<\/rt><\/ruby>う","type":"u","eng":"visit, ask (humble)"},
        {"kanji":"<ruby>生<rt>う<\/rt><\/ruby>む","type":"u","eng":"give birth"},
        {"kanji":"<ruby>埋<rt>う<\/rt><\/ruby>める","type":"ru","eng":"bury"},
        {"kanji":"<ruby>教<rt>おそ<\/rt><\/ruby>わる","type":"u","eng":"be taught"},
        {"kanji":"<ruby>断<rt>ことわ<\/rt><\/ruby>る","type":"u","eng":"refuse, reject"},
        {"kanji":"<ruby>転<rt>ころ<\/rt><\/ruby>ぶ","type":"u","eng":"fall down"},
        {"kanji":"<ruby>騒<rt>さわ<\/rt><\/ruby>ぐ","type":"u","eng":"make a noise"},
        {"kanji":"<ruby>育<rt>そだ<\/rt><\/ruby>つ","type":"u","eng":"grow up"},
        {"kanji":"<ruby>抱<rt>だ<\/rt><\/ruby>く","type":"u","eng":"hug, embrace"},
        {"kanji":"<ruby>黙<rt>だま<\/rt><\/ruby>る","type":"u","eng":"be silent"},
        {"kanji":"<ruby>貯<rt>た<\/rt><\/ruby>める","type":"ru","eng":"save (money)"},
        {"kanji":"<ruby>確<rt>たし<\/rt><\/ruby>かめる","type":"ru","eng":"confirm"},
        {"kanji":"<ruby>捕<rt>つか<\/rt><\/ruby>まる","type":"u","eng":"be caught"},
        {"kanji":"<ruby>包<rt>つつ<\/rt><\/ruby>む","type":"u","eng":"wrap"},
        {"kanji":"<ruby>連<rt>つ<\/rt><\/ruby>れてくる","type":"irv","eng":"bring someone"},
        {"kanji":"<ruby>解<rt>と<\/rt><\/ruby>く","type":"u","eng":"solve"},
        {"kanji":"<ruby>通<rt>とお<\/rt><\/ruby>る","type":"u","eng":"pass by"},
        {"kanji":"<ruby>直<rt>なお<\/rt><\/ruby>す","type":"u","eng":"repair, fix"},
        {"kanji":"<ruby>直<rt>なお<\/rt><\/ruby>る","type":"u","eng":"be repaired"},
        {"kanji":"<ruby>撫<rt>な<\/rt><\/ruby>でる","type":"ru","eng":"stroke, pet"},
        {"kanji":"<ruby>投<rt>な<\/rt><\/ruby>げる","type":"ru","eng":"throw"},
        {"kanji":"<ruby>盗<rt>ぬす<\/rt><\/ruby>む","type":"u","eng":"steal"},
        {"kanji":"<ruby>祈<rt>いの<\/rt><\/ruby>る","type":"u","eng":"pray"},
        {"kanji":"<ruby>祝<rt>いわ<\/rt><\/ruby>う","type":"u","eng":"celebrate"},
        {"kanji":"<ruby>植<rt>う<\/rt><\/ruby>える","type":"ru","eng":"plant"},
        {"kanji":"<ruby>疑<rt>うたが<\/rt><\/ruby>う","type":"u","eng":"doubt"},
        {"kanji":"<ruby>失<rt>うしな<\/rt><\/ruby>う","type":"u","eng":"lose"},
        {"kanji":"<ruby>噛<rt>か<\/rt><\/ruby>む","type":"u","eng":"bite, chew"},
        {"kanji":"<ruby>刻<rt>きざ<\/rt><\/ruby>む","type":"u","eng":"carve, chop"},
        {"kanji":"<ruby>組<rt>く<\/rt><\/ruby>む","type":"u","eng":"assemble, fold (arms)"},
        {"kanji":"<ruby>配<rt>くば<\/rt><\/ruby>る","type":"u","eng":"distribute"},
        {"kanji":"<ruby>比<rt>くら<\/rt><\/ruby>べる","type":"ru","eng":"compare"},
        {"kanji":"<ruby>越<rt>こ<\/rt><\/ruby>える","type":"ru","eng":"cross over"},
        {"kanji":"<ruby>越<rt>こ<\/rt><\/ruby>す","type":"u","eng":"pass, move (house)"},
        {"kanji":"<ruby>逆<rt>さか<\/rt><\/ruby>らう","type":"u","eng":"oppose, go against"},
        {"kanji":"<ruby>冷<rt>さ<\/rt><\/ruby>める","type":"ru","eng":"cool down (intransitive)"},
        {"kanji":"<ruby>支<rt>ささ<\/rt><\/ruby>える","type":"ru","eng":"support"},
        {"kanji":"<ruby>囁<rt>ささや<\/rt><\/ruby>く","type":"u","eng":"whisper"},
        {"kanji":"<ruby>刺<rt>さ<\/rt><\/ruby>す","type":"u","eng":"stab, sting"},
        {"kanji":"<ruby>冷<rt>さ<\/rt><\/ruby>ます","type":"u","eng":"cool down (transitive)"},
        {"kanji":"<ruby>妨<rt>さまた<\/rt><\/ruby>げる","type":"ru","eng":"hinder, prevent"},
        {"kanji":"<ruby>強<rt>し<\/rt><\/ruby>いる","type":"ru","eng":"force"},
        {"kanji":"<ruby>沈<rt>しず<\/rt><\/ruby>む","type":"u","eng":"sink"},
        {"kanji":"<ruby>従<rt>したが<\/rt><\/ruby>う","type":"u","eng":"obey, follow"},
        {"kanji":"<ruby>支払<rt>しはら<\/rt><\/ruby>う","type":"u","eng":"pay"},
        {"kanji":"<ruby>絞<rt>しぼ<\/rt><\/ruby>る","type":"u","eng":"squeeze"},
        {"kanji":"<ruby>占<rt>し<\/rt><\/ruby>める","type":"ru","eng":"occupy, hold"},
        {"kanji":"<ruby>喋<rt>しゃべ<\/rt><\/ruby>る","type":"u","eng":"chat, talk"},
        {"kanji":"<ruby>救<rt>すく<\/rt><\/ruby>う","type":"u","eng":"save, rescue"},
        {"kanji":"<ruby>優<rt>やさ<\/rt><\/ruby>れる","type":"ru","eng":"excel, be superior"},
        {"kanji":"<ruby>汚<rt>よご<\/rt><\/ruby>す","type":"u","eng":"dirty (something)"},
        {"kanji":"<ruby>振<rt>ふ<\/rt><\/ruby>り返る","type":"u","eng":"look back"},
        {"kanji":"<ruby>目指<rt>めざ<\/rt><\/ruby>す","type":"u","eng":"aim for"},
        {"kanji":"<ruby>求<rt>もと<\/rt><\/ruby>める","type":"ru","eng":"request, seek"},
        {"kanji":"<ruby>許<rt>ゆる<\/rt><\/ruby>す","type":"u","eng":"forgive, allow"},
        {"kanji":"<ruby>寄<rt>よ<\/rt><\/ruby>せる","type":"ru","eng":"bring near, collect"},
        {"kanji":"<ruby>分<rt>わ<\/rt><\/ruby>け<ruby>合<rt>あ<\/rt><\/ruby>う","type":"u","eng":"share"},
        {"kanji":"<ruby>整<rt>ととの<\/rt><\/ruby>える","type":"ru","eng":"arrange, put in order"},
        {"kanji":"<ruby>教<rt>おそ<\/rt><\/ruby>わる","type":"u","eng":"be taught"},
        {"kanji":"<ruby>重<rt>かさ<\/rt><\/ruby>なる","type":"u","eng":"be piled up, overlap"},
        {"kanji":"<ruby>片付<rt>かたづ<\/rt><\/ruby>く","type":"u","eng":"be put in order"},
        {"kanji":"<ruby>気<rt>き<\/rt><\/ruby>を<ruby>付<rt>つ<\/rt><\/ruby>ける","type":"ru","eng":"be careful"},
        {"kanji":"<ruby>好<rt>この<\/rt><\/ruby>む","type":"u","eng":"prefer, like"},
        {"kanji":"<ruby>転<rt>ころ<\/rt><\/ruby>がす","type":"u","eng":"roll (something)"},
        {"kanji":"<ruby>囁<rt>ささや<\/rt><\/ruby>く","type":"u","eng":"whisper"},
        {"kanji":"<ruby>黙<rt>だま<\/rt><\/ruby>る","type":"u","eng":"be silent"}
    ],
    "adjectives": [
        {"kanji":"いい","type":"ira","eng":"good"},
        {"kanji":"かっこいい","type":"ira","eng":"cool, handsome"},
        {"kanji":"<ruby>赤<rt>あか<\/rt><\/ruby>い","type":"i","eng":"red"},
        {"kanji":"<ruby>新<rt>あたら<\/rt><\/ruby>しい","type":"i","eng":"new"},
        {"kanji":"<ruby>暑<rt>あつ<\/rt><\/ruby>い","type":"i","eng":"hot (weather)"},
        {"kanji":"<ruby>危<rt>あぶ<\/rt><\/ruby>ない","type":"i","eng":"dangerous"},
        {"kanji":"<ruby>美<rt>お<\/rt><\/ruby><ruby>味<rt>い<\/rt><\/ruby>しい","type":"i","eng":"delicious"},
        {"kanji":"<ruby>大<rt>おお<\/rt><\/ruby>きい","type":"i","eng":"big"},
        {"kanji":"<ruby>遅<rt>おそ<\/rt><\/ruby>い","type":"i","eng":"late, slow"},
        {"kanji":"<ruby>面<rt>おも<\/rt><\/ruby><ruby>白<rt>しろ<\/rt><\/ruby>い","type":"i","eng":"interesting, funny"},
        {"kanji":"<ruby>可<rt>か<\/rt><\/ruby><ruby>愛<rt>わい<\/rt><\/ruby>い","type":"i","eng":"cute, pretty"},
        {"kanji":"<ruby>寒<rt>さむ<\/rt><\/ruby>い","type":"i","eng":"cold (weather)"},
        {"kanji":"<ruby>高<rt>たか<\/rt><\/ruby>い","type":"i","eng":"high, expensive"},
        {"kanji":"<ruby>楽<rt>たの<\/rt><\/ruby>しい","type":"i","eng":"fun, pleasant"},
        {"kanji":"<ruby>小<rt>ちい<\/rt><\/ruby>さい","type":"i","eng":"small"},
        {"kanji":"<ruby>詰<rt>つま<\/rt><\/ruby>らない","type":"i","eng":"uninteresting, boring","altOkurigana":["詰まらない"]},
        {"kanji":"<ruby>速<rt>はや<\/rt><\/ruby>い","type":"i","eng":"fast, quick"},
        {"kanji":"<ruby>古<rt>ふる<\/rt><\/ruby>い","type":"i","eng":"old (thing)"},
        {"kanji":"<ruby>欲<rt>ほ<\/rt><\/ruby>しい","type":"i","eng":"wanted, desired"},
        {"kanji":"<ruby>難<rt>むずか<\/rt><\/ruby>しい","type":"i","eng":"difficult"},
        {"kanji":"<ruby>安<rt>やす<\/rt><\/ruby>い","type":"i","eng":"cheap"},
        {"kanji":"<ruby>好<rt>す<\/rt><\/ruby>き","type":"na","eng":"like"},
        {"kanji":"<ruby>有<rt>ゆう<\/rt><\/ruby><ruby>名<rt>めい<\/rt><\/ruby>","type":"na","eng":"famous"},
        {"kanji":"きれい","type":"na","eng":"beautiful, tidy"},
        {"kanji":"<ruby>嫌<rt>きら<\/rt><\/ruby>い","type":"na","eng":"dislike"},
        {"kanji":"<ruby>静<rt>しず<\/rt><\/ruby>か","type":"na","eng":"quiet"},
        {"kanji":"<ruby>元<rt>げん<\/rt><\/ruby><ruby>気<rt>き<\/rt><\/ruby>","type":"na","eng":"healthy"},
        {"kanji":"<ruby>色<rt>いろ<\/rt><\/ruby><ruby>々<rt>いろ<\/rt><\/ruby>","type":"na","eng":"various"},
        {"kanji":"<ruby>心<rt>しん<\/rt><\/ruby><ruby>配<rt>ぱい<\/rt><\/ruby>","type":"na","eng":"worry, care"},
        {"kanji":"<ruby>嫌<rt>いや<\/rt><\/ruby>","type":"na","eng":"unpleasant, detestable"},
        {"kanji":"<ruby>十<rt>じゅう<\/rt><\/ruby><ruby>分<rt>ぶん<\/rt><\/ruby>","type":"na","eng":"sufficient"},
        {"kanji":"<ruby>立<rt>りっ<\/rt><\/ruby><ruby>派<rt>ぱ<\/rt><\/ruby>","type":"na","eng":"excellent, splendid"},
        {"kanji":"<ruby>同<rt>おな<\/rt><\/ruby>じ","type":"na","eng":"same, alike"},
        {"kanji":"<ruby>大<rt>だい<\/rt><\/ruby><ruby>丈<rt>じょう<\/rt><\/ruby><ruby>夫<rt>ぶ<\/rt><\/ruby>","type":"na","eng":"okay, safe"},
        {"kanji":"<ruby>真<rt>ま<\/rt><\/ruby>っ<ruby>直<rt>す<\/rt><\/ruby>ぐ","type":"na","eng":"straight, direct","altOkurigana":["真直ぐ","真すぐ","真っすぐ"]},
        {"kanji":"<ruby>下<rt>へ<\/rt><\/ruby><ruby>手<rt>た<\/rt><\/ruby>","type":"na","eng":"unskilled"},
        {"kanji":"<ruby>簡<rt>かん<\/rt><\/ruby>簡単<rt>たん<\/rt><\/ruby>","type":"na","eng":"simple, easy"},
        {"kanji":"<ruby>楽<rt>らく<\/rt><\/ruby>","type":"na","eng":"comfortable, easy"},
        {"kanji":"<ruby>残<rt>ざん<\/rt><\/ruby><ruby>念<rt>ねん<\/rt><\/ruby>","type":"na","eng":"unfortunate, disappointing"},
        {"kanji":"<ruby>必<rt>ひつ<\/rt><\/ruby><ruby>要<rt>よう<\/rt><\/ruby>","type":"na","eng":"necessary"},
        {"kanji":"<ruby>忙<rt>いそが<\/rt><\/ruby>しい","type":"i","eng":"busy"},
        {"kanji":"<ruby>明<rt>あか<\/rt><\/ruby>るい","type":"i","eng":"bright, cheerful"},
        {"kanji":"<ruby>温<rt>あたた<\/rt><\/ruby>かい","type":"i","eng":"warm"},
        {"kanji":"<ruby>厚<rt>あつ<\/rt><\/ruby>い","type":"i","eng":"thick"},
        {"kanji":"<ruby>甘<rt>あま<\/rt><\/ruby>い","type":"i","eng":"sweet"},
        {"kanji":"<ruby>危<rt>あぶ<\/rt><\/ruby>ない","type":"i","eng":"dangerous"},
        {"kanji":"<ruby>痛<rt>いた<\/rt><\/ruby>い","type":"i","eng":"painful"},
        {"kanji":"<ruby>薄<rt>うす<\/rt><\/ruby>い","type":"i","eng":"thin"},
        {"kanji":"<ruby>嬉<rt>うれ<\/rt><\/ruby>しい","type":"i","eng":"happy, glad"},
        {"kanji":"<ruby>重<rt>おも<\/rt><\/ruby>い","type":"i","eng":"heavy"},
        {"kanji":"<ruby>軽<rt>かる<\/rt><\/ruby>い","type":"i","eng":"light"},
        {"kanji":"<ruby>辛<rt>から<\/rt><\/ruby>い","type":"i","eng":"spicy, salty"},
        {"kanji":"<ruby>厳<rt>きび<\/rt><\/ruby>しい","type":"i","eng":"strict"},
        {"kanji":"<ruby>汚<rt>きたな<\/rt><\/ruby>い","type":"i","eng":"dirty"},
        {"kanji":"<ruby>暗<rt>くら<\/rt><\/ruby>い","type":"i","eng":"dark"},
        {"kanji":"<ruby>苦<rt>くる<\/rt><\/ruby>しい","type":"i","eng":"painful, distressing"},
        {"kanji":"<ruby>詳<rt>くわ<\/rt><\/ruby>しい","type":"i","eng":"detailed, knowledgeable"},
        {"kanji":"<ruby>煙<rt>けむ<\/rt><\/ruby>い","type":"i","eng":"smoky"},
        {"kanji":"<ruby>凄<rt>すご<\/rt><\/ruby>い","type":"i","eng":"amazing, great"},
        {"kanji":"<ruby>素晴<rt>すば<\/rt><\/ruby>らしい","type":"i","eng":"wonderful"},
        {"kanji":"<ruby>滑<rt>すべ<\/rt><\/ruby>っこい","type":"i","eng":"slippery"},
        {"kanji":"<ruby>狭<rt>せま<\/rt><\/ruby>い","type":"i","eng":"narrow"},
        {"kanji":"<ruby>正<rt>ただ<\/rt><\/ruby>しい","type":"i","eng":"correct"},
        {"kanji":"<ruby>近<rt>ちか<\/rt><\/ruby>い","type":"i","eng":"near"},
        {"kanji":"<ruby>強<rt>つよ<\/rt><\/ruby>い","type":"i","eng":"strong"},
        {"kanji":"<ruby>冷<rt>つめ<\/rt><\/ruby>たい","type":"i","eng":"cold (to touch)"},
        {"kanji":"<ruby>弱<rt>よわ<\/rt><\/ruby>い","type":"i","eng":"weak"},
        {"kanji":"<ruby>若<rt>わか<\/rt><\/ruby>い","type":"i","eng":"young"},
        {"kanji":"<ruby>鋭<rt>えび<\/rt><\/ruby>い","type":"i","eng":"sharp"},
        {"kanji":"<ruby>恐<rt>おそ<\/rt><\/ruby>ろしい","type":"i","eng":"terrifying"},
        {"kanji":"<ruby>柔<rt>やわ<\/rt><\/ruby>らかい","type":"i","eng":"soft"},
        {"kanji":"<ruby>丸<rt>まる<\/rt><\/ruby>い","type":"i","eng":"round"},
        {"kanji":"<ruby>鋭<rt>するど<\/rt><\/ruby>い","type":"i","eng":"sharp, keen"},
        {"kanji":"<ruby>鈍<rt>にぶ<\/rt><\/ruby>い","type":"i","eng":"dull, slow"},
        {"kanji":"<ruby>苦<rt>にが<\/rt><\/ruby>い","type":"i","eng":"bitter"},
        {"kanji":"<ruby>深<rt>ふか<\/rt><\/ruby>い","type":"i","eng":"deep"},
        {"kanji":"<ruby>浅<rt>あさ<\/rt><\/ruby>い","type":"i","eng":"shallow"},
        {"kanji":"<ruby>太<rt>ふと<\/rt><\/ruby>い","type":"i","eng":"thick, fat"},
        {"kanji":"<ruby>細<rt>ほそ<\/rt><\/ruby>い","type":"i","eng":"thin, slender"},
        {"kanji":"<ruby>珍<rt>めずら<\/rt><\/ruby>しい","type":"i","eng":"rare"},
        {"kanji":"<ruby>優<rt>やさ<\/rt><\/ruby>しい","type":"i","eng":"kind"},
        {"kanji":"<ruby>易<rt>やさ<\/rt><\/ruby>しい","type":"i","eng":"easy"},
        {"kanji":"<ruby>宜<rt>よろ<\/rt><\/ruby>しい","type":"i","eng":"good (formal)"},
        {"kanji":"<ruby>酷<rt>ひど<\/rt><\/ruby>い","type":"i","eng":"cruel, awful"},
        {"kanji":"<ruby>恥<rt>は<\/rt><\/ruby>ずかしい","type":"i","eng":"embarrassing"},
        {"kanji":"<ruby>羨<rt>うらや<\/rt><\/ruby>ましい","type":"i","eng":"envious"},
        {"kanji":"<ruby>懐<rt>なつ<\/rt><\/ruby>かしい","type":"i","eng":"nostalgic"},
        {"kanji":"<ruby>煩<rt>うるさ<\/rt><\/ruby>い","type":"i","eng":"noisy, annoying"},
        {"kanji":"<ruby>醜<rt>みにく<\/rt><\/ruby>い","type":"i","eng":"ugly"},
        {"kanji":"<ruby>賢<rt>かしこ<\/rt><\/ruby>い","type":"i","eng":"wise, clever"},
        {"kanji":"<ruby>醜<rt>みにく<\/rt><\/ruby>い","type":"i","eng":"ugly"},
        {"kanji":"<ruby>緩<rt>ゆる<\/rt><\/ruby>い","type":"i","eng":"loose"},
        {"kanji":"<ruby>鈍<rt>にぶ<\/rt><\/ruby>い","type":"i","eng":"dull"},
        {"kanji":"<ruby>賢<rt>かしこ<\/rt><\/ruby>い","type":"i","eng":"wise"},
        {"kanji":"<ruby>荒<rt>あら<\/rt><\/ruby>い","type":"i","eng":"rough, violent"},
        {"kanji":"<ruby>臭<rt>くさ<\/rt><\/ruby>い","type":"i","eng":"smelly"},
        {"kanji":"<ruby>塩辛<rt>しおから<\/rt><\/ruby>い","type":"i","eng":"salty"},
        {"kanji":"<ruby>酸<rt>す<\/rt><\/ruby>っぱい","type":"i","eng":"sour"},
        {"kanji":"<ruby>冷<rt>ひ<\/rt><\/ruby>ややか","type":"na","eng":"cool, calm"},
        {"kanji":"<ruby>爽<rt>さわ<\/rt><\/ruby>やか","type":"na","eng":"refreshing"},
        {"kanji":"<ruby>鮮<rt>あざ<\/rt><\/ruby>やか","type":"na","eng":"vivid"},
        {"kanji":"<ruby>賑<rt>にぎ<\/rt><\/ruby>やか","type":"na","eng":"lively"},
        {"kanji":"<ruby>穏<rt>おだ<\/rt><\/ruby>やか","type":"na","eng":"gentle, calm"},
        {"kanji":"<ruby>健<rt>すこ<\/rt><\/ruby>やか","type":"na","eng":"healthy"},
        {"kanji":"<ruby>和<rt>なご<\/rt><\/ruby>やか","type":"na","eng":"harmonious"},
        {"kanji":"<ruby>細<rt>こま<\/rt><\/ruby>か","type":"na","eng":"fine, minute"},
        {"kanji":"<ruby>密<rt>ひそ<\/rt><\/ruby>か","type":"na","eng":"secret, private"},
        {"kanji":"<ruby>疎<rt>おろそ<\/rt><\/ruby>か","type":"na","eng":"negligent"},
        {"kanji":"<ruby>愚<rt>おろ<\/rt><\/ruby>か","type":"na","eng":"foolish"},
        {"kanji":"<ruby>静<rt>しず<\/rt><\/ruby>か","type":"na","eng":"quiet"},
        {"kanji":"<ruby>豊<rt>ゆた<\/rt><\/ruby>か","type":"na","eng":"rich, abundant"},
        {"kanji":"<ruby>遥<rt>はる<\/rt><\/ruby>か","type":"na","eng":"distant, far"},
        {"kanji":"<ruby>僅<rt>わず<\/rt><\/ruby>か","type":"na","eng":"slight, few"},
        {"kanji":"<ruby>密<rt>ひそ<\/rt><\/ruby>か","type":"na","eng":"secret"},
        {"kanji":"<ruby>滑<rt>なめ<\/rt><\/ruby>らか","type":"na","eng":"smooth"},
        {"kanji":"<ruby>清<rt>きよ<\/rt><\/ruby>らか","type":"na","eng":"pure"},
        {"kanji":"<ruby>明<rt>あき<\/rt><\/ruby>らか","type":"na","eng":"obvious, clear"},
        {"kanji":"<ruby>安<rt>やす<\/rt><\/ruby>らか","type":"na","eng":"peaceful"},
        {"kanji":"<ruby>朗<rt>ほが<\/rt><\/ruby>らか","type":"na","eng":"cheerful"},
        {"kanji":"<ruby>便<rt>べん<\/rt><\/ruby><ruby>利<rt>り<\/rt><\/ruby>","type":"na","eng":"convenient"},
        {"kanji":"<ruby>不<rt>ふ<\/rt><\/ruby><ruby>便<rt>べん<\/rt><\/ruby>","type":"na","eng":"inconvenient"},
        {"kanji":"<ruby>親<rt>しん<\/rt><\/ruby><ruby>切<rt>せつ<\/rt><\/ruby>","type":"na","eng":"kind"},
        {"kanji":"<ruby>不<rt>ふ<\/rt><\/ruby><ruby>親<rt>しん<\/rt><\/ruby><ruby>切<rt>せつ<\/rt><\/ruby>","type":"na","eng":"unkind"},
        {"kanji":"<ruby>丁<rt>てい<\/rt><\/ruby><ruby>寧<rt>ねい<\/rt><\/ruby>","type":"na","eng":"polite"},
        {"kanji":"<ruby>失<rt>れい<\/rt><\/ruby><ruby>礼<rt>れい<\/rt><\/ruby>","type":"na","eng":"rude"},
        {"kanji":"<ruby>上<rt>じょう<\/rt><\/ruby><ruby>手<rt>ず<\/rt><\/ruby>","type":"na","eng":"skillful"},
        {"kanji":"<ruby>下<rt>へ<\/rt><\/ruby><ruby>手<rt>た<\/rt><\/ruby>","type":"na","eng":"unskillful"},
        {"kanji":"<ruby>大<rt>だい<\/rt><\/ruby><ruby>好<rt>す<\/rt><\/ruby>き","type":"na","eng":"love, very fond of"},
        {"kanji":"<ruby>大<rt>だい<\/rt><\/ruby><ruby>嫌<rt>きら<\/rt><\/ruby>い","type":"na","eng":"hate"},
        {"kanji":"<ruby>得<rt>とく<\/rt><\/ruby><ruby>意<rt>い<\/rt><\/ruby>","type":"na","eng":"good at"},
        {"kanji":"<ruby>苦<rt>にが<\/rt><\/ruby><ruby>手<rt>て<\/rt><\/ruby>","type":"na","eng":"bad at"},
        {"kanji":"<ruby>幸<rt>しあわ<\/rt><\/ruby>せ","type":"na","eng":"happy"},
        {"kanji":"<ruby>変<rt>へん<\/rt><\/ruby>","type":"na","eng":"strange"},
        {"kanji":"<ruby>無<rt>む<\/rt><\/ruby><ruby>駄<rt>だ<\/rt><\/ruby>","type":"na","eng":"wasteful"},
        {"kanji":"<ruby>無<rt>む<\/rt><\/ruby><ruby>理<rt>り<\/rt><\/ruby>","type":"na","eng":"impossible"},
        {"kanji":"<ruby>不<rt>ふ<\/rt><\/ruby><ruby>可<rt>か<\/rt><\/ruby><ruby>能<rt>のう<\/rt><\/ruby>","type":"na","eng":"impossible"},
        {"kanji":"<ruby>可<rt>か<\/rt><\/ruby><ruby>能<rt>のう<\/rt><\/ruby>","type":"na","eng":"possible"},
        {"kanji":"<ruby>特<rt>とく<\/rt><\/ruby><ruby>別<rt>べつ<\/rt><\/ruby>","type":"na","eng":"special"},
        {"kanji":"<ruby>大<rt>たい<\/rt><\/ruby><ruby>切<rt>せつ<\/rt><\/ruby>","type":"na","eng":"important"},
        {"kanji":"<ruby>大<rt>だい<\/rt><\/ruby><ruby>事<rt>じ<\/rt><\/ruby>","type":"na","eng":"important, serious"},
        {"kanji":"<ruby>必<rt>ひつ<\/rt><\/ruby><ruby>要<rt>よう<\/rt><\/ruby>","type":"na","eng":"necessary"},
        {"kanji":"<ruby>不<rt>ふ<\/rt><\/ruby><ruby>必<rt>ひつ<\/rt><\/ruby><ruby>要<rt>よう<\/rt><\/ruby>","type":"na","eng":"unnecessary"},
        {"kanji":"<ruby>主<rt>おも<\/rt><\/ruby>","type":"na","eng":"main"},
        {"kanji":"<ruby>複<rt>ふく<\/rt><\/ruby><ruby>雑<rt>ざつ<\/rt><\/ruby>","type":"na","eng":"complex"},
        {"kanji":"<ruby>簡<rt>かん<\/rt><\/ruby><ruby>単<rt>たん<\/rt><\/ruby>","type":"na","eng":"simple"},
        {"kanji":"<ruby>明<rt>めい<\/rt><\/ruby><ruby>確<rt>かく<\/rt><\/ruby>","type":"na","eng":"clear"},
        {"kanji":"<ruby>正<rt>せい<\/rt><\/ruby><ruby>確<rt>かく<\/rt><\/ruby>","type":"na","eng":"accurate"},
        {"kanji":"<ruby>適<rt>てき<\/rt><\/ruby><ruby>切<rt>せつ<\/rt><\/ruby>","type":"na","eng":"appropriate"},
        {"kanji":"<ruby>不<rt>ふ<\/rt><ruby>適<rt>てき<\/rt><\/ruby><ruby>切<rt>せつ<\/rt><\/ruby>","type":"na","eng":"inappropriate"},
        {"kanji":"<ruby>完<rt>かん<\/rt><\/ruby><ruby>全<rt>ぜん<\/rt><\/ruby>","type":"na","eng":"perfect, complete"},
        {"kanji":"<ruby>不<rt>ふ<\/rt><\/ruby><ruby>完<rt>かん<\/rt><\/ruby><ruby>全<rt>ぜん<\/rt><\/ruby>","type":"na","eng":"incomplete"},
        {"kanji":"<ruby>険<rt>けん<\/rt><\/ruby><ruby>悪<rt>あく<\/rt><\/ruby>","type":"na","eng":"hostile"},
        {"kanji":"<ruby>誠<rt>せい<\/rt><\/ruby><ruby>実<rt>じつ<\/rt><\/ruby>","type":"na","eng":"sincere"},
        {"kanji":"<ruby>正<rt>しょう<\/rt><\/ruby><ruby>直<rt>じき<\/rt><\/ruby>","type":"na","eng":"honest"},
        {"kanji":"<ruby>素<rt>す<\/rt><\/ruby><ruby>直<rt>なお<\/rt><\/ruby>","type":"na","eng":"docile, honest"},
        {"kanji":"<ruby>健<rt>けん<\/rt><\/ruby><ruby>康<rt>こう<\/rt><\/ruby>","type":"na","eng":"healthy"},
        {"kanji":"<ruby>不<rt>ふ<\/rt><\/ruby><ruby>健<rt>けん<\/rt><\/ruby><ruby>康<rt>こう<\/rt><\/ruby>","type":"na","eng":"unhealthy"},
        {"kanji":"<ruby>清<rt>せい<\/rt><\/ruby><ruby>潔<rt>けつ<\/rt><\/ruby>","type":"na","eng":"clean, hygienic"},
        {"kanji":"<ruby>不<rt>ふ<\/rt><\/ruby><ruby>潔<rt>けつ<\/rt><\/ruby>","type":"na","eng":"unhygienic"},
        {"kanji":"<ruby>謙<rt>けん<\/rt><\/ruby><ruby>虚<rt>きょ<\/rt><\/ruby>","type":"na","eng":"humble"},
        {"kanji":"<ruby>頑<rt>がん<\/rt><\/ruby><ruby>固<rt>こ<\/rt><\/ruby>","type":"na","eng":"stubborn"},
        {"kanji":"<ruby>我<rt>わが<\/rt><\/ruby><ruby>儘<rt>まま<\/rt><\/ruby>","type":"na","eng":"selfish"},
        {"kanji":"<ruby>勝<rt>かっ<\/rt><\/ruby><ruby>手<rt>て<\/rt><\/ruby>","type":"na","eng":"selfish, one's own way"},
        {"kanji":"<ruby>適<rt>てき<\/rt><\/ruby><ruby>当<rt>とう<\/rt><\/ruby>","type":"na","eng":"random, appropriate"},
        {"kanji":"<ruby>真<rt>ま<\/rt><\/ruby><ruby>面<rt>め<\/rt><\/ruby><ruby>目<rt>め<\/rt><\/ruby>","type":"na","eng":"serious, diligent"},
        {"kanji":"<ruby>気<rt>き<\/rt><\/ruby><ruby>楽<rt>らく<\/rt><\/ruby>","type":"na","eng":"carefree"},
        {"kanji":"<ruby>退<rt>たい<\/rt><\/ruby><ruby>屈<rt>くつ<\/rt><\/ruby>","type":"na","eng":"boring"},
        {"kanji":"<ruby>平<rt>へい<\/rt><\/ruby><ruby>気<rt>き<\/rt><\/ruby>","type":"na","eng":"fine, unconcerned"},
        {"kanji":"<ruby>平<rt>へい<\/rt><\/ruby><ruby>和<rt>わ<\/rt><\/ruby>","type":"na","eng":"peaceful"},
        {"kanji":"<ruby>必<rt>ひつ<\/rt><\/ruby><ruby>死<rt>し<\/rt><\/ruby>","type":"na","eng":"desperate"},
        {"kanji":"<ruby>懸<rt>けん<\/rt><\/ruby><ruby>命<rt>めい<\/rt><\/ruby>","type":"na","eng":"eager, strenuous"},
        {"kanji":"<ruby>熱<rt>ねっ<\/rt><\/ruby><ruby>心<rt>しん<\/rt><\/ruby>","type":"na","eng":"enthusiastic"},
        {"kanji":"<ruby>夢<rt>む<\/rt><\/ruby><ruby>中<rt>ちゅう<\/rt><\/ruby>","type":"na","eng":"absorbed, obsessed"},
        {"kanji":"<ruby>得意<rt>とくい<\/rt><\/ruby>","type":"na","eng":"one's strong point"},
        {"kanji":"<ruby>不得意<rt>ふとくい<\/rt><\/ruby>","type":"na","eng":"one's weak point"},
        {"kanji":"<ruby>満足<rt>まんぞく<\/rt><\/ruby>","type":"na","eng":"satisfied"},
        {"kanji":"<ruby>不満<rt>ふまん<\/rt><\/ruby>","type":"na","eng":"dissatisfied"},
        {"kanji":"<ruby>幸運<rt>こううん<\/rt><\/ruby>","type":"na","eng":"lucky"},
        {"kanji":"<ruby>不運<rt>ふうん<\/rt><\/ruby>","type":"na","eng":"unlucky"},
        {"kanji":"<ruby>便利<rt>べんり<\/rt><\/ruby>","type":"na","eng":"convenient"},
        {"kanji":"<ruby>邪魔<rt>じゃま<\/rt><\/ruby>","type":"na","eng":"hindrance, nuisance"},
        {"kanji":"<ruby>下等<rt>かとう<\/rt><\/ruby>","type":"na","eng":"inferior"},
        {"kanji":"<ruby>上等<rt>じょうとう<\/rt><\/ruby>","type":"na","eng":"superior, first-class"},
        {"kanji":"<ruby>貧乏<rt>びんぼう<\/rt><\/ruby>","type":"na","eng":"poor"},
        {"kanji":"<ruby>贅沢<rt>ぜいたく<\/rt><\/ruby>","type":"na","eng":"luxurious"},
        {"kanji":"<ruby>派手<rt>はで<\/rt><\/ruby>","type":"na","eng":"flashy"},
        {"kanji":"<ruby>地味<rt>じみ<\/rt><\/ruby>","type":"na","eng":"plain, sober"},
        {"kanji":"<ruby>粋<rt>いき<\/rt><\/ruby>","type":"na","eng":"chic, stylish"},
        {"kanji":"<ruby>無愛想<rt>ぶあいそう<\/rt><\/ruby>","type":"na","eng":"unsociable, blunt"},
        {"kanji":"<ruby>器用<rt>きよう<\/rt><\/ruby>","type":"na","eng":"skillful, handy"},
        {"kanji":"<ruby>不器用<rt>ぶきよう<\/rt><\/ruby>","type":"na","eng":"clumsy"},
        {"kanji":"<ruby>丁寧<rt>ていねい<\/rt><\/ruby>","type":"na","eng":"polite, careful"},
        {"kanji":"<ruby>乱暴<rt>らんぼう<\/rt><\/ruby>","type":"na","eng":"violent, rough"},
        {"kanji":"<ruby>利口<rt>りこう<\/rt><\/ruby>","type":"na","eng":"clever, smart"},
        {"kanji":"<ruby>馬鹿<rt>ばか<\/rt><\/ruby>","type":"na","eng":"foolish, stupid"},
        {"kanji":"<ruby>有名<rt>ゆうめい<\/rt><\/ruby>","type":"na","eng":"famous"},
        {"kanji":"<ruby>無名<rt>むめい<\/rt><\/ruby>","type":"na","eng":"unknown"},
        {"kanji":"<ruby>立派<rt>りっぱ<\/rt><\/ruby>","type":"na","eng":"splendid, fine"},
        {"kanji":"<ruby>見事<rt>みごと<\/rt><\/ruby>","type":"na","eng":"splendid, great"},
        {"kanji":"<ruby>大切<rt>たいせつ<\/rt><\/ruby>","type":"na","eng":"precious"},
        {"kanji":"<ruby>身軽<rt>みがる<\/rt><\/ruby>","type":"na","eng":"agile, light"},
        {"kanji":"<ruby>残酷<rt>ざんこく<\/rt><\/ruby>","type":"na","eng":"cruel"},
        {"kanji":"<ruby>冷淡<rt>れいたん<\/rt><\/ruby>","type":"na","eng":"indifferent, cold"},
        {"kanji":"<ruby>公平<rt>こうへい<\/rt><\/ruby>","type":"na","eng":"fair"},
        {"kanji":"<ruby>不公平<rt>ふこうへい<\/rt><\/ruby>","type":"na","eng":"unfair"},
        {"kanji":"<ruby>透明<rt>とうめい<\/rt><\/ruby>","type":"na","eng":"transparent"},
        {"kanji":"<ruby>新鮮<rt>しんせん<\/rt><\/ruby>","type":"na","eng":"fresh"},
        {"kanji":"<ruby>詳細<rt>しょうさい<\/rt><\/ruby>","type":"na","eng":"detailed"},
        {"kanji":"<ruby>巨大<rt>きょだい<\/rt><\/ruby>","type":"na","eng":"huge, gigantic"},
        {"kanji":"<ruby>卑劣<rt>ひれつ<\/rt><\/ruby>","type":"na","eng":"mean, despicable"},
        {"kanji":"<ruby>優雅<rt>ゆうが<\/rt><\/ruby>","type":"na","eng":"elegant"},
        {"kanji":"<ruby>気軽<rt>きがる<\/rt><\/ruby>","type":"na","eng":"lighthearted"},
        {"kanji":"<ruby>窮屈<rt>きゅうくつ<\/rt><\/ruby>","type":"na","eng":"tight, cramped"},
        {"kanji":"<ruby>迅速<rt>じんそく<\/rt><\/ruby>","type":"na","eng":"quick, prompt"},
        {"kanji":"<ruby>丁寧<rt>ていねい<\/rt><\/ruby>","type":"na","eng":"polite"},
        {"kanji":"<ruby>強引<rt>ごういん<\/rt><\/ruby>","type":"na","eng":"pushy, forced"},
        {"kanji":"<ruby>優秀<rt>ゆうしゅう<\/rt><\/ruby>","type":"na","eng":"excellent"},
        {"kanji":"<ruby>華やか<rt>はなやか<\/rt><\/ruby>","type":"na","eng":"showy, brilliant"},
        {"kanji":"<ruby>密接<rt>みっせつ<\/rt><\/ruby>","type":"na","eng":"close, intimate"},
        {"kanji":"<ruby>適切<rt>てきせつ<\/rt><\/ruby>","type":"na","eng":"appropriate"},
        {"kanji":"<ruby>気軽<rt>きがる<\/rt><\/ruby>","type":"na","eng":"casual"}
    ]
}