export const wordData = {
    "verbs": [
        {"kanji":"行く","reading":"いく","type":"irv","eng":"go", "group": "iku"},
        {"kanji":"する","reading":"する","type":"irv","eng":"do, make", "group": "suru"},
        {"kanji":"来る","reading":"くる","type":"irv","eng":"come"},
        {"kanji":"ある","reading":"ある","type":"irv","eng":"have, exists, is (inanimate)"},
        {"kanji":"問う","reading":"とう","type":"irv","eng":"ask, accuse"},
        {"kanji":"いる","reading":"いる","type":"ru","eng":"exists, is (living things)"},
        {"kanji":"始める","reading":"はじめる","type":"ru","eng":"begin"},
        {"kanji":"借りる","reading":"かりる","type":"ru","eng":"borrow, rent"},
        {"kanji":"続ける","reading":"つづける","type":"ru","eng":"continue, proceed"},
        {"kanji":"決める","reading":"きめる","type":"ru","eng":"decide, choose"},
        {"kanji":"食べる","reading":"たべる","type":"ru","eng":"eat"},
        {"kanji":"忘れる","reading":"わすれる","type":"ru","eng":"forget"},
        {"kanji":"降りる","reading":"おりる","type":"ru","eng":"get off, go down"},
        {"kanji":"疲れる","reading":"つかれる","type":"ru","eng":"get tired"},
        {"kanji":"起きる","reading":"おきる","type":"ru","eng":"get up, wake up"},
        {"kanji":"あげる","reading":"あげる","type":"ru","eng":"give"},
        {"kanji":"出る","reading":"でる","type":"ru","eng":"leave, exit, appear"},
        {"kanji":"助ける","reading":"たすける","type":"ru","eng":"help"},
        {"kanji":"見る","reading":"みる","type":"ru","eng":"see, look"},
        {"kanji":"開ける","reading":"あける","type":"ru","eng":"open"},
        {"kanji":"覚える","reading":"おぼえる","type":"ru","eng":"remember, learn"},
        {"kanji":"寝る","reading":"ねる","type":"ru","eng":"sleep, go to bed"},
        {"kanji":"閉める","reading":"しめる","type":"ru","eng":"close"},
        {"kanji":"着る","reading":"きる","type":"ru","eng":"put on, wear (shirt, jacket, etc)"},
        {"kanji":"なる","reading":"なる","type":"u","eng":"become"},
        {"kanji":"乗る","reading":"のる","type":"u","eng":"board, ride"},
        {"kanji":"切る","reading":"きる","type":"u","eng":"cut"},
        {"kanji":"やる","reading":"やる","type":"u","eng":"do, give"},
        {"kanji":"終わる","reading":"おわる","type":"u","eng":"end"},
        {"kanji":"上がる","reading":"あがる","type":"u","eng":"go up, rise","altOkurigana":["上る"]},
        {"kanji":"知る","reading":"しる","type":"u","eng":"know"},
        {"kanji":"作る","reading":"つくる","type":"u","eng":"make, build"},
        {"kanji":"帰る","reading":"かえる","type":"u","eng":"return, go home"},
        {"kanji":"取る","reading":"とる","type":"u","eng":"take, steal"},
        {"kanji":"買う","reading":"かう","type":"u","eng":"buy"},
        {"kanji":"笑う","reading":"わらう","type":"u","eng":"laugh, smile"},
        {"kanji":"会う","reading":"あう","type":"u","eng":"meet"},
        {"kanji":"言う","reading":"いう","type":"u","eng":"say, utter"},
        {"kanji":"思う","reading":"おもう","type":"u","eng":"think, believe"},
        {"kanji":"使う","reading":"つかう","type":"u","eng":"use"},
        {"kanji":"持つ","reading":"もつ","type":"u","eng":"hold, have"},
        {"kanji":"待つ","reading":"まつ","type":"u","eng":"wait"},
        {"kanji":"立つ","reading":"たつ","type":"u","eng":"stand up"},
        {"kanji":"聞く","reading":"きく","type":"u","eng":"hear, listen"},
        {"kanji":"引く","reading":"ひく","type":"u","eng":"pull, tug"},
        {"kanji":"履く","reading":"はく","type":"u","eng":"put on, wear (pants, skirt, shoes, etc)"},
        {"kanji":"歩く","reading":"あるく","type":"u","eng":"walk"},
        {"kanji":"書く","reading":"かく","type":"u","eng":"write"},
        {"kanji":"働く","reading":"はたらく","type":"u","eng":"work"},
        {"kanji":"死ぬ","reading":"しぬ","type":"u","eng":"die, pass away"},
        {"kanji":"飲む","reading":"のむ","type":"u","eng":"drink"},
        {"kanji":"楽しむ","reading":"たのしむ","type":"u","eng":"enjoy, have fun"},
        {"kanji":"進む","reading":"すすむ","type":"u","eng":"advance, go forward"},
        {"kanji":"住む","reading":"すむ","type":"u","eng":"live, inhabit"},
        {"kanji":"読む","reading":"よむ","type":"u","eng":"read"},
        {"kanji":"休む","reading":"やすむ","type":"u","eng":"rest, be absent"},
        {"kanji":"遊ぶ","reading":"あそぶ","type":"u","eng":"play, have a good time"},
        {"kanji":"学ぶ","reading":"まなぶ","type":"u","eng":"study, learn"},
        {"kanji":"選ぶ","reading":"えらぶ","type":"u","eng":"choose, select"},
        {"kanji":"返す","reading":"かえす","type":"u","eng":"return (something), put back"},
        {"kanji":"押す","reading":"おす","type":"u","eng":"push, press"},
        {"kanji":"治す","reading":"なおす","type":"u","eng":"cure, repair"},
        {"kanji":"話す","reading":"はなす","type":"u","eng":"talk, speak"},
        {"kanji":"探す","reading":"さがす","type":"u","eng":"search, look for"},
        {"kanji":"貸す","reading":"かす","type":"u","eng":"lend, loan"},
        {"kanji":"泳ぐ","reading":"およぐ","type":"u","eng":"swim"},
        {"kanji":"脱ぐ","reading":"ぬぐ","type":"u","eng":"take off clothes, undress"},
        {"kanji":"急ぐ","reading":"いそぐ","type":"u","eng":"hurry"},
        {"kanji":"稼ぐ","reading":"かせぐ","type":"u","eng":"earn income, make money"},
        {"kanji":"寛ぐ","reading":"くつろぐ","type":"u","eng":"relax, feel at home"},
        {"kanji":"繋ぐ","reading":"つなぐ","type":"u","eng":"connect, link together"},
        {"kanji":"分かる","reading":"わかる","type":"u","eng":"understand"},
        {"kanji":"勉強する","reading":"べんきょうする","type":"irv","eng":"study", "group": "suru"},
        {"kanji":"受け持つ","reading":"うけもつ","type":"u","eng":"take charge of"},
        {"kanji":"持って行く","reading":"もっていく","type":"irv","eng":"take, carry away", "group": "iku"},
        {"kanji":"食べ歩く","reading":"たべあるく","type":"u","eng":"try food at various restaurants"},
        {"kanji":"洗う","reading":"あらう","type":"u","eng":"wash"},
        {"kanji":"受ける","reading":"うける","type":"ru","eng":"receive, take (an exam)"},
        {"kanji":"動く","reading":"うごく","type":"u","eng":"move"},
        {"kanji":"歌う","reading":"うたう","type":"u","eng":"sing"},
        {"kanji":"写す","reading":"うつす","type":"u","eng":"copy, photograph"},
        {"kanji":"映る","reading":"うつる","type":"u","eng":"be reflected"},
        {"kanji":"選ぶ","reading":"えらぶ","type":"u","eng":"choose"},
        {"kanji":"送る","reading":"おくる","type":"u","eng":"send"},
        {"kanji":"置く","reading":"おく","type":"u","eng":"put, place"},
        {"kanji":"遅れる","reading":"おくれる","type":"ru","eng":"be late"},
        {"kanji":"起こす","reading":"おこす","type":"u","eng":"wake someone up"},
        {"kanji":"行う","reading":"おこなう","type":"u","eng":"perform, conduct"},
        {"kanji":"怒る","reading":"おこる","type":"u","eng":"get angry"},
        {"kanji":"教える","reading":"おしえる","type":"ru","eng":"teach, inform"},
        {"kanji":"落とす","reading":"おとす","type":"u","eng":"drop"},
        {"kanji":"落ちる","reading":"おちる","type":"ru","eng":"fall"},
        {"kanji":"踊る","reading":"おどる","type":"u","eng":"dance"},
        {"kanji":"驚く","reading":"おどろく","type":"u","eng":"be surprised"},
        {"kanji":"思い出す","reading":"おもいだす","type":"u","eng":"recall, remember"},
        {"kanji":"折る","reading":"おる","type":"u","eng":"break, fold"},
        {"kanji":"下りる","reading":"おりる","type":"ru","eng":"descend"},
        {"kanji":"替える","reading":"かえる","type":"ru","eng":"exchange, replace"},
        {"kanji":"掛ける","reading":"かける","type":"ru","eng":"hang, sit, call"},
        {"kanji":"飾る","reading":"かざる","type":"u","eng":"decorate"},
        {"kanji":"勝つ","reading":"かつ","type":"u","eng":"win"},
        {"kanji":"片付ける","reading":"かたづける","type":"ru","eng":"tidy up"},
        {"kanji":"通う","reading":"かよう","type":"u","eng":"commute"},
        {"kanji":"乾く","reading":"かわく","type":"u","eng":"dry (intransitive)"},
        {"kanji":"乾かす","reading":"かわかす","type":"u","eng":"dry (transitive)"},
        {"kanji":"考える","reading":"かんがえる","type":"ru","eng":"think, consider"},
        {"kanji":"感じる","reading":"かんじる","type":"ru","eng":"feel"},
        {"kanji":"頑張る","reading":"がんばる","type":"u","eng":"do one's best"},
        {"kanji":"消える","reading":"きえる","type":"ru","eng":"go out, vanish"},
        {"kanji":"聞こえる","reading":"きこえる","type":"ru","eng":"be audible"},
        {"kanji":"決まる","reading":"きまる","type":"u","eng":"be decided"},
        {"kanji":"決める","reading":"きめる","type":"ru","eng":"decide"},
        {"kanji":"消す","reading":"けす","type":"u","eng":"erase, turn off"},
        {"kanji":"答える","reading":"こたえる","type":"ru","eng":"answer"},
        {"kanji":"困る","reading":"こまる","type":"u","eng":"be in trouble"},
        {"kanji":"壊す","reading":"こわす","type":"u","eng":"break (transitive)"},
        {"kanji":"壊れる","reading":"こわれる","type":"ru","eng":"break (intransitive)"},
        {"kanji":"探す","reading":"さがす","type":"u","eng":"search for"},
        {"kanji":"下がる","reading":"さがる","type":"u","eng":"go down"},
        {"kanji":"下げる","reading":"さげる","type":"ru","eng":"lower"},
        {"kanji":"差す","reading":"さす","type":"u","eng":"point, hold (umbrella)"},
        {"kanji":"騒ぐ","reading":"さわぐ","type":"u","eng":"make noise"},
        {"kanji":"触る","reading":"さわる","type":"u","eng":"touch"},
        {"kanji":"叱る","reading":"しかる","type":"u","eng":"scold"},
        {"kanji":"信じる","reading":"しんじる","type":"ru","eng":"believe"},
        {"kanji":"閉まる","reading":"しまる","type":"u","eng":"close (intransitive)"},
        {"kanji":"知らせる","reading":"しらせる","type":"ru","eng":"notify"},
        {"kanji":"調べる","reading":"しらべる","type":"ru","eng":"investigate, look up"},
        {"kanji":"過ぎる","reading":"すぎる","type":"ru","eng":"pass, exceed"},
        {"kanji":"空く","reading":"すく","type":"u","eng":"become empty, hungry"},
        {"kanji":"進める","reading":"すすめる","type":"ru","eng":"advance, promote"},
        {"kanji":"捨てる","reading":"すてる","type":"ru","eng":"throw away"},
        {"kanji":"滑る","reading":"すべる","type":"u","eng":"slip"},
        {"kanji":"済む","reading":"すむ","type":"u","eng":"finish, conclude"},
        {"kanji":"座る","reading":"すわる","type":"u","eng":"sit"},
        {"kanji":"育てる","reading":"そだてる","type":"ru","eng":"raise, rear"},
        {"kanji":"倒れる","reading":"たおれる","type":"ru","eng":"fall over"},
        {"kanji":"助かる","reading":"たすかる","type":"u","eng":"be saved"},
        {"kanji":"訪ねる","reading":"たずねる","type":"ru","eng":"visit"},
        {"kanji":"尋ねる","reading":"たずねる","type":"ru","eng":"ask, inquire"},
        {"kanji":"建てる","reading":"たてる","type":"ru","eng":"build"},
        {"kanji":"頼む","reading":"たのむ","type":"u","eng":"request, ask"},
        {"kanji":"足りる","reading":"たりる","type":"ru","eng":"be sufficient"},
        {"kanji":"捕まえる","reading":"つかまえる","type":"ru","eng":"catch, arrest"},
        {"kanji":"疲れる","reading":"つかれる","type":"ru","eng":"get tired"},
        {"kanji":"着く","reading":"つく","type":"u","eng":"arrive"},
        {"kanji":"付ける","reading":"つける","type":"ru","eng":"attach, turn on"},
        {"kanji":"伝える","reading":"つたえる","type":"ru","eng":"convey"},
        {"kanji":"続く","reading":"つづく","type":"u","eng":"continue (intransitive)"},
        {"kanji":"包む","reading":"つつむ","type":"u","eng":"wrap"},
        {"kanji":"連れる","reading":"つれる","type":"ru","eng":"lead, take along"},
        {"kanji":"手伝う","reading":"てつだう","type":"u","eng":"help"},
        {"kanji":"通る","reading":"とおる","type":"u","eng":"pass through"},
        {"kanji":"届ける","reading":"とどける","type":"ru","eng":"deliver"},
        {"kanji":"止まる","reading":"とまる","type":"u","eng":"stop"},
        {"kanji":"泊まる","reading":"とまる","type":"u","eng":"stay overnight"},
        {"kanji":"止める","reading":"とめる","type":"ru","eng":"stop, park"},
        {"kanji":"取り替える","reading":"とりかえる","type":"ru","eng":"exchange"},
        {"kanji":"取る","reading":"とる","type":"u","eng":"take, handle"},
        {"kanji":"直る","reading":"なおる","type":"u","eng":"be repaired"},
        {"kanji":"治る","reading":"なおる","type":"u","eng":"be cured"},
        {"kanji":"泣く","reading":"なく","type":"u","eng":"cry"},
        {"kanji":"亡くなる","reading":"なくなる","type":"u","eng":"die, pass away"},
        {"kanji":"無くなる","reading":"なくなる","type":"u","eng":"be lost, run out"},
        {"kanji":"投げる","reading":"なげる","type":"ru","eng":"throw"},
        {"kanji":"鳴る","reading":"なる","type":"u","eng":"ring, sound"},
        {"kanji":"並ぶ","reading":"ならぶ","type":"u","eng":"line up (intransitive)"},
        {"kanji":"並べる","reading":"ならべる","type":"ru","eng":"line up (transitive)"},
        {"kanji":"慣れる","reading":"なれる","type":"ru","eng":"get used to"},
        {"kanji":"逃げる","reading":"にげる","type":"ru","eng":"escape"},
        {"kanji":"似る","reading":"にる","type":"ru","eng":"resemble"},
        {"kanji":"脱ぐ","reading":"ぬぐ","type":"u","eng":"take off (clothes)"},
        {"kanji":"盗む","reading":"ぬすむ","type":"u","eng":"steal"},
        {"kanji":"塗る","reading":"ぬる","type":"u","eng":"paint, spread"},
        {"kanji":"濡れる","reading":"ぬれる","type":"ru","eng":"get wet"},
        {"kanji":"願う","reading":"ねがう","type":"u","eng":"wish, request"},
        {"kanji":"眠る","reading":"ねむる","type":"u","eng":"sleep"},
        {"kanji":"登る","reading":"のぼる","type":"u","eng":"climb"},
        {"kanji":"乗り換える","reading":"のりかえる","type":"ru","eng":"transfer (trains)"},
        {"kanji":"運ぶ","reading":"はこぶ","type":"u","eng":"carry"},
        {"kanji":"始まる","reading":"はじまる","type":"u","eng":"begin (intransitive)"},
        {"kanji":"外す","reading":"はずす","type":"u","eng":"remove, unfasten"},
        {"kanji":"払う","reading":"はらう","type":"u","eng":"pay"},
        {"kanji":"晴れる","reading":"はれる","type":"ru","eng":"clear up (weather)"},
        {"kanji":"光る","reading":"ひかる","type":"u","eng":"shine"},
        {"kanji":"引き出す","reading":"ひきだす","type":"u","eng":"withdraw"},
        {"kanji":"冷やす","reading":"ひやす","type":"u","eng":"cool down"},
        {"kanji":"拾う","reading":"ひろう","type":"u","eng":"pick up"},
        {"kanji":"増える","reading":"ふえる","type":"ru","eng":"increase"},
        {"kanji":"吹く","reading":"ふく","type":"u","eng":"blow"},
        {"kanji":"太る","reading":"ふとる","type":"u","eng":"gain weight"},
        {"kanji":"踏む","reading":"ふむ","type":"u","eng":"step on"},
        {"kanji":"振る","reading":"ふる","type":"u","eng":"wave, shake"},
        {"kanji":"降る","reading":"ふる","type":"u","eng":"fall (rain, snow)"},
        {"kanji":"減る","reading":"へる","type":"u","eng":"decrease"},
        {"kanji":"褒める","reading":"ほめる","type":"ru","eng":"praise"},
        {"kanji":"参る","reading":"まいる","type":"u","eng":"go, come (humble)"},
        {"kanji":"負ける","reading":"まける","type":"ru","eng":"lose"},
        {"kanji":"混ぜる","reading":"まぜる","type":"ru","eng":"mix"},
        {"kanji":"間違える","reading":"まちがえる","type":"ru","eng":"make a mistake"},
        {"kanji":"守る","reading":"まもる","type":"u","eng":"protect, obey"},
        {"kanji":"回る","reading":"まわる","type":"u","eng":"rotate, turn"},
        {"kanji":"見つかる","reading":"みつかる","type":"u","eng":"be found"},
        {"kanji":"見つける","reading":"みつける","type":"ru","eng":"find"},
        {"kanji":"向かう","reading":"むかう","type":"u","eng":"face, head toward"},
        {"kanji":"迎える","reading":"むかえる","type":"ru","eng":"welcome, meet"},
        {"kanji":"召し上がる","reading":"めしあがる","type":"ru","eng":"eat, drink (respectful)"},
        {"kanji":"申す","reading":"もうす","type":"u","eng":"say (humble)"},
        {"kanji":"戻る","reading":"もどる","type":"u","eng":"return"},
        {"kanji":"貰う","reading":"もらう","type":"u","eng":"receive"},
        {"kanji":"焼く","reading":"やく","type":"u","eng":"bake, grill"},
        {"kanji":"痩せる","reading":"やせる","type":"ru","eng":"lose weight"},
        {"kanji":"休める","reading":"やすめる","type":"ru","eng":"rest (transitive)"},
        {"kanji":"止める","reading":"やめる","type":"ru","eng":"stop, quit"},
        {"kanji":"汚れる","reading":"よごれる","type":"ru","eng":"get dirty"},
        {"kanji":"呼ぶ","reading":"よぶ","type":"u","eng":"call"},
        {"kanji":"寄る","reading":"よる","type":"u","eng":"stop by"},
        {"kanji":"喜ぶ","reading":"よろこぶ","type":"u","eng":"be glad"},
        {"kanji":"沸かす","reading":"わかす","type":"u","eng":"boil (water)"},
        {"kanji":"分かれる","reading":"わかれる","type":"ru","eng":"separate, split"},
        {"kanji":"沸く","reading":"わく","type":"u","eng":"boil (intransitive)"},
        {"kanji":"渡す","reading":"わたす","type":"u","eng":"hand over"},
        {"kanji":"渡る","reading":"わたる","type":"u","eng":"cross (bridge, street)"},
        {"kanji":"割る","reading":"わる","type":"u","eng":"divide, break"},
        {"kanji":"打つ","reading":"うつ","type":"u","eng":"hit, strike"},
        {"kanji":"折れる","reading":"おれる","type":"ru","eng":"be broken"},
        {"kanji":"伺う","reading":"うかがう","type":"u","eng":"visit, ask (humble)"},
        {"kanji":"生む","reading":"うむ","type":"u","eng":"give birth"},
        {"kanji":"埋める","reading":"うめる","type":"ru","eng":"bury"},
        {"kanji":"教わる","reading":"おそわる","type":"u","eng":"be taught"},
        {"kanji":"断る","reading":"ことわる","type":"u","eng":"refuse, reject"},
        {"kanji":"転ぶ","reading":"ころぶ","type":"u","eng":"fall down"},
        {"kanji":"騒ぐ","reading":"さわぐ","type":"u","eng":"make a noise"},
        {"kanji":"育つ","reading":"そだつ","type":"u","eng":"grow up"},
        {"kanji":"抱く","reading":"だく","type":"u","eng":"hug, embrace"},
        {"kanji":"黙る","reading":"だまる","type":"u","eng":"be silent"},
        {"kanji":"貯める","reading":"ためる","type":"ru","eng":"save (money)"},
        {"kanji":"確かめる","reading":"たしかめる","type":"ru","eng":"confirm"},
        {"kanji":"捕まる","reading":"つかまる","type":"u","eng":"be caught"},
        {"kanji":"包む","reading":"つつむ","type":"u","eng":"wrap"},
        {"kanji":"連れてくる","reading":"つれてくる","type":"irv","eng":"bring someone"},
        {"kanji":"解く","reading":"とく","type":"u","eng":"solve"},
        {"kanji":"通る","reading":"とおる","type":"u","eng":"pass by"},
        {"kanji":"直す","reading":"なおす","type":"u","eng":"repair, fix"},
        {"kanji":"直る","reading":"なおる","type":"u","eng":"be repaired"},
        {"kanji":"撫でる","reading":"なでる","type":"ru","eng":"stroke, pet"},
        {"kanji":"投げる","reading":"なげる","type":"ru","eng":"throw"},
        {"kanji":"盗む","reading":"ぬすむ","type":"u","eng":"steal"},
        {"kanji":"祈る","reading":"いのる","type":"u","eng":"pray"},
        {"kanji":"祝う","reading":"いわう","type":"u","eng":"celebrate"},
        {"kanji":"植える","reading":"うえる","type":"ru","eng":"plant"},
        {"kanji":"疑う","reading":"うたがう","type":"u","eng":"doubt"},
        {"kanji":"失う","reading":"うしなう","type":"u","eng":"lose"},
        {"kanji":"噛む","reading":"かむ","type":"u","eng":"bite, chew"},
        {"kanji":"刻む","reading":"きざむ","type":"u","eng":"carve, chop"},
        {"kanji":"組む","reading":"くむ","type":"u","eng":"assemble, fold (arms)"},
        {"kanji":"配る","reading":"くばる","type":"u","eng":"distribute"},
        {"kanji":"比べる","reading":"くらべる","type":"ru","eng":"compare"},
        {"kanji":"越える","reading":"こえる","type":"ru","eng":"cross over"},
        {"kanji":"越す","reading":"こす","type":"u","eng":"pass, move (house)"},
        {"kanji":"逆らう","reading":"さからう","type":"u","eng":"oppose, go against"},
        {"kanji":"冷める","reading":"さめる","type":"ru","eng":"cool down (intransitive)"},
        {"kanji":"支える","reading":"ささえる","type":"ru","eng":"support"},
        {"kanji":"囁く","reading":"ささやく","type":"u","eng":"whisper"},
        {"kanji":"刺す","reading":"さす","type":"u","eng":"stab, sting"},
        {"kanji":"冷ます","reading":"さます","type":"u","eng":"cool down (transitive)"},
        {"kanji":"妨げる","reading":"さまたげる","type":"ru","eng":"hinder, prevent"},
        {"kanji":"強いる","reading":"しいる","type":"ru","eng":"force"},
        {"kanji":"沈む","reading":"しずむ","type":"u","eng":"sink"},
        {"kanji":"従う","reading":"したがう","type":"u","eng":"obey, follow"},
        {"kanji":"支払う","reading":"しはらう","type":"u","eng":"pay"},
        {"kanji":"絞る","reading":"しぼる","type":"u","eng":"squeeze"},
        {"kanji":"占める","reading":"しめる","type":"ru","eng":"occupy, hold"},
        {"kanji":"喋る","reading":"しゃべる","type":"u","eng":"chat, talk"},
        {"kanji":"救う","reading":"すくう","type":"u","eng":"save, rescue"},
        {"kanji":"優れる","reading":"すぐれる","type":"ru","eng":"excel, be superior"},
        {"kanji":"汚す","reading":"よごす","type":"u","eng":"dirty (something)"},
        {"kanji":"振り返る","reading":"ふりかえる","type":"u","eng":"look back"},
        {"kanji":"目指す","reading":"めざす","type":"u","eng":"aim for"},
        {"kanji":"求める","reading":"もとめる","type":"ru","eng":"request, seek"},
        {"kanji":"許す","reading":"ゆるす","type":"u","eng":"forgive, allow"},
        {"kanji":"寄せる","reading":"よせる","type":"ru","eng":"bring near, collect"},
        {"kanji":"分け合う","reading":"わけあう","type":"u","eng":"share"},
        {"kanji":"整える","reading":"ととのえる","type":"ru","eng":"arrange, put in order"},
        {"kanji":"教わる","reading":"おそわる","type":"u","eng":"be taught"},
        {"kanji":"重なる","reading":"かさなる","type":"u","eng":"be piled up, overlap"},
        {"kanji":"片付く","reading":"かたづく","type":"u","eng":"be put in order"},
        {"kanji":"気を付ける","reading":"きをつける","type":"ru","eng":"be careful"},
        {"kanji":"好む","reading":"このむ","type":"u","eng":"prefer, like"},
        {"kanji":"転がす","reading":"ころがす","type":"u","eng":"roll (something)"},
        {"kanji":"囁く","reading":"ささやく","type":"u","eng":"whisper"},
        {"kanji":"黙る","reading":"だまる","type":"u","eng":"be silent"}
    ],
    "adjectives": [
        {"kanji":"いい","reading":"いい","type":"ira","eng":"good"},
        {"kanji":"かっこいい","reading":"かっこいい","type":"ira","eng":"cool, handsome"},
        {"kanji":"赤い","reading":"あかい","type":"i","eng":"red"},
        {"kanji":"新しい","reading":"あたらしい","type":"i","eng":"new"},
        {"kanji":"暑い","reading":"あつい","type":"i","eng":"hot (weather)"},
        {"kanji":"危ない","reading":"あぶない","type":"i","eng":"dangerous"},
        {"kanji":"美味しい","reading":"おいしい","type":"i","eng":"delicious"},
        {"kanji":"大きい","reading":"おおきい","type":"i","eng":"big"},
        {"kanji":"遅い","reading":"おそい","type":"i","eng":"late, slow"},
        {"kanji":"面白い","reading":"おもしろい","type":"i","eng":"interesting, funny"},
        {"kanji":"可愛い","reading":"かわいい","type":"i","eng":"cute, pretty"},
        {"kanji":"寒い","reading":"さむい","type":"i","eng":"cold (weather)"},
        {"kanji":"高い","reading":"たかい","type":"i","eng":"high, expensive"},
        {"kanji":"楽しい","reading":"たのしい","type":"i","eng":"fun, pleasant"},
        {"kanji":"小さい","reading":"ちいさい","type":"i","eng":"small"},
        {"kanji":"詰まらない","reading":"つまらない","type":"i","eng":"uninteresting, boring","altOkurigana":["詰まらない"]},
        {"kanji":"速い","reading":"はやい","type":"i","eng":"fast, quick"},
        {"kanji":"古い","reading":"ふるい","type":"i","eng":"old (thing)"},
        {"kanji":"欲しい","reading":"ほしい","type":"i","eng":"wanted, desired"},
        {"kanji":"難しい","reading":"むずかしい","type":"i","eng":"difficult"},
        {"kanji":"安い","reading":"やすい","type":"i","eng":"cheap"},
        {"kanji":"好き","reading":"すき","type":"na","eng":"like"},
        {"kanji":"有名","reading":"ゆうめい","type":"na","eng":"famous"},
        {"kanji":"きれい","reading":"きれい","type":"na","eng":"beautiful, tidy"},
        {"kanji":"嫌い","reading":"きらい","type":"na","eng":"dislike"},
        {"kanji":"静か","reading":"しずか","type":"na","eng":"quiet"},
        {"kanji":"元気","reading":"げんき","type":"na","eng":"healthy"},
        {"kanji":"色々","reading":"いろいろ","type":"na","eng":"various"},
        {"kanji":"心配","reading":"しんぱい","type":"na","eng":"worry, care"},
        {"kanji":"嫌","reading":"いや","type":"na","eng":"unpleasant, detestable"},
        {"kanji":"十分","reading":"じゅうぶん","type":"na","eng":"sufficient"},
        {"kanji":"立派","reading":"りっぱ","type":"na","eng":"excellent, splendid"},
        {"kanji":"同じ","reading":"おなじ","type":"na","eng":"same, alike"},
        {"kanji":"大丈夫","reading":"だいじょうぶ","type":"na","eng":"okay, safe"},
        {"kanji":"真っ直ぐ","reading":"まっすぐ","type":"na","eng":"straight, direct","altOkurigana":["真直ぐ","真すぐ","真っすぐ"]},
        {"kanji":"下手","reading":"へた","type":"na","eng":"unskilled"},
        {"kanji":"簡単","reading":"かんたん","type":"na","eng":"simple, easy"},
        {"kanji":"楽","reading":"らく","type":"na","eng":"comfortable, easy"},
        {"kanji":"残念","reading":"ざんねん","type":"na","eng":"unfortunate, disappointing"},
        {"kanji":"必要","reading":"ひつよう","type":"na","eng":"necessary"},
        {"kanji":"忙しい","reading":"いそがしい","type":"i","eng":"busy"},
        {"kanji":"明るい","reading":"あかるい","type":"i","eng":"bright, cheerful"},
        {"kanji":"温かい","reading":"あたたかい","type":"i","eng":"warm"},
        {"kanji":"厚い","reading":"あつい","type":"i","eng":"thick"},
        {"kanji":"甘い","reading":"あまい","type":"i","eng":"sweet"},
        {"kanji":"危ない","reading":"あぶない","type":"i","eng":"dangerous"},
        {"kanji":"痛い","reading":"いたい","type":"i","eng":"painful"},
        {"kanji":"薄い","reading":"うすい","type":"i","eng":"thin"},
        {"kanji":"嬉しい","reading":"うれしい","type":"i","eng":"happy, glad"},
        {"kanji":"重い","reading":"おもい","type":"i","eng":"heavy"},
        {"kanji":"軽い","reading":"かるい","type":"i","eng":"light"},
        {"kanji":"辛い","reading":"からい","type":"i","eng":"spicy, salty"},
        {"kanji":"厳しい","reading":"きびしい","type":"i","eng":"strict"},
        {"kanji":"汚い","reading":"きたない","type":"i","eng":"dirty"},
        {"kanji":"暗い","reading":"くらい","type":"i","eng":"dark"},
        {"kanji":"苦しい","reading":"くるしい","type":"i","eng":"painful, distressing"},
        {"kanji":"詳しい","reading":"くわしい","type":"i","eng":"detailed, knowledgeable"},
        {"kanji":"煙い","reading":"けむい","type":"i","eng":"smoky"},
        {"kanji":"凄い","reading":"すごい","type":"i","eng":"amazing, great"},
        {"kanji":"素晴らしい","reading":"すばらしい","type":"i","eng":"wonderful"},
        {"kanji":"滑っこい","reading":"すべっこい","type":"i","eng":"slippery"},
        {"kanji":"狭い","reading":"せまい","type":"i","eng":"narrow"},
        {"kanji":"正しい","reading":"ただしい","type":"i","eng":"correct"},
        {"kanji":"近い","reading":"ちかい","type":"i","eng":"near"},
        {"kanji":"強い","reading":"つよい","type":"i","eng":"strong"},
        {"kanji":"冷たい","reading":"つめたい","type":"i","eng":"cold (to touch)"},
        {"kanji":"弱い","reading":"よわい","type":"i","eng":"weak"},
        {"kanji":"若い","reading":"わかい","type":"i","eng":"young"},
        {"kanji":"鋭い","reading":"するどい","type":"i","eng":"sharp"},
        {"kanji":"恐ろしい","reading":"おそろしい","type":"i","eng":"terrifying"},
        {"kanji":"柔らかい","reading":"やわらかい","type":"i","eng":"soft"},
        {"kanji":"丸い","reading":"まるい","type":"i","eng":"round"},
        {"kanji":"鈍い","reading":"にぶい","type":"i","eng":"dull, slow"},
        {"kanji":"苦い","reading":"にがい","type":"i","eng":"bitter"},
        {"kanji":"深い","reading":"ふかい","type":"i","eng":"deep"},
        {"kanji":"浅い","reading":"あさい","type":"i","eng":"shallow"},
        {"kanji":"太い","reading":"ふとい","type":"i","eng":"thick, fat"},
        {"kanji":"細い","reading":"ほそい","type":"i","eng":"thin, slender"},
        {"kanji":"珍しい","reading":"めずらしい","type":"i","eng":"rare"},
        {"kanji":"優しい","reading":"やさしい","type":"i","eng":"kind"},
        {"kanji":"易しい","reading":"やさしい","type":"i","eng":"easy"},
        {"kanji":"宜しい","reading":"よろしい","type":"i","eng":"good (formal)"},
        {"kanji":"酷い","reading":"ひどい","type":"i","eng":"cruel, awful"},
        {"kanji":"恥ずかしい","reading":"はずかしい","type":"i","eng":"embarrassing"},
        {"kanji":"羨ましい","reading":"うらやましい","type":"i","eng":"envious"},
        {"kanji":"懐かしい","reading":"なつかしい","type":"i","eng":"nostalgic"},
        {"kanji":"煩い","reading":"うるさい","type":"i","eng":"noisy, annoying"},
        {"kanji":"醜い","reading":"みにくい","type":"i","eng":"ugly"},
        {"kanji":"賢い","reading":"かしこい","type":"i","eng":"wise, clever"},
        {"kanji":"緩い","reading":"ゆるい","type":"i","eng":"loose"},
        {"kanji":"荒い","reading":"あらい","type":"i","eng":"rough, violent"},
        {"kanji":"臭い","reading":"くさい","type":"i","eng":"smelly"},
        {"kanji":"塩辛い","reading":"しおからい","type":"i","eng":"salty"},
        {"kanji":"酸っぱい","reading":"すっぱい","type":"i","eng":"sour"},
        {"kanji":"冷ややか","reading":"ひややか","type":"na","eng":"cool, calm"},
        {"kanji":"爽やか","reading":"さわやか","type":"na","eng":"refreshing"},
        {"kanji":"鮮やか","reading":"あざやか","type":"na","eng":"vivid"},
        {"kanji":"賑やか","reading":"にぎやか","type":"na","eng":"lively"},
        {"kanji":"穏やか","reading":"おだやか","type":"na","eng":"gentle, calm"},
        {"kanji":"健やか","reading":"すこやか","type":"na","eng":"healthy"},
        {"kanji":"和やか","reading":"なごやか","type":"na","eng":"harmonious"},
        {"kanji":"細か","reading":"こまか","type":"na","eng":"fine, minute"},
        {"kanji":"密か","reading":"ひそか","type":"na","eng":"secret, private"},
        {"kanji":"疎か","reading":"おろそか","type":"na","eng":"negligent"},
        {"kanji":"愚か","reading":"おろか","type":"na","eng":"foolish"},
        {"kanji":"静か","reading":"しずか","type":"na","eng":"quiet"},
        {"kanji":"豊か","reading":"ゆたか","type":"na","eng":"rich, abundant"},
        {"kanji":"遥か","reading":"はるか","type":"na","eng":"distant, far"},
        {"kanji":"僅か","reading":"わずか","type":"na","eng":"slight, few"},
        {"kanji":"滑らか","reading":"なめらか","type":"na","eng":"smooth"},
        {"kanji":"清らか","reading":"きよらか","type":"na","eng":"pure"},
        {"kanji":"明らか","reading":"あきらか","type":"na","eng":"obvious, clear"},
        {"kanji":"安らか","reading":"やすらか","type":"na","eng":"peaceful"},
        {"kanji":"朗らか","reading":"ほがらか","type":"na","eng":"cheerful"},
        {"kanji":"便利","reading":"べんり","type":"na","eng":"convenient"},
        {"kanji":"不便","reading":"ふべん","type":"na","eng":"inconvenient"},
        {"kanji":"親切","reading":"しんせつ","type":"na","eng":"kind"},
        {"kanji":"不親切","reading":"ふしんせつ","type":"na","eng":"unkind"},
        {"kanji":"丁寧","reading":"ていねい","type":"na","eng":"polite"},
        {"kanji":"失礼","reading":"しつれい","type":"na","eng":"rude"},
        {"kanji":"上手","reading":"じょうず","type":"na","eng":"skillful"},
        {"kanji":"下手","reading":"へた","type":"na","eng":"unskillful"},
        {"kanji":"大好き","reading":"だいすき","type":"na","eng":"love, very fond of"},
        {"kanji":"大嫌い","reading":"だいきらい","type":"na","eng":"hate"},
        {"kanji":"得意","reading":"とくい","type":"na","eng":"good at"},
        {"kanji":"苦手","reading":"にがて","type":"na","eng":"bad at"},
        {"kanji":"幸せ","reading":"しあわせ","type":"na","eng":"happy"},
        {"kanji":"変","reading":"へん","type":"na","eng":"strange"},
        {"kanji":"無駄","reading":"むだ","type":"na","eng":"wasteful"},
        {"kanji":"無理","reading":"むり","type":"na","eng":"impossible"},
        {"kanji":"不可能","reading":"ふかのう","type":"na","eng":"impossible"},
        {"kanji":"可能","reading":"かのう","type":"na","eng":"possible"},
        {"kanji":"特別","reading":"とくべつ","type":"na","eng":"special"},
        {"kanji":"大切","reading":"たいせつ","type":"na","eng":"important"},
        {"kanji":"大事","reading":"だいじ","type":"na","eng":"important, serious"},
        {"kanji":"必要","reading":"ひつよう","type":"na","eng":"necessary"},
        {"kanji":"不必要","reading":"ふひつよう","type":"na","eng":"unnecessary"},
        {"kanji":"主","reading":"おも","type":"na","eng":"main"},
        {"kanji":"複雑","reading":"ふくざつ","type":"na","eng":"complex"},
        {"kanji":"明確","reading":"めいかく","type":"na","eng":"clear"},
        {"kanji":"正確","reading":"せいかく","type":"na","eng":"accurate"},
        {"kanji":"適切","reading":"てきせつ","type":"na","eng":"appropriate"},
        {"kanji":"不適切","reading":"ふてきせつ","type":"na","eng":"inappropriate"},
        {"kanji":"完全","reading":"かんぜん","type":"na","eng":"perfect, complete"},
        {"kanji":"不完全","reading":"ふかんぜん","type":"na","eng":"incomplete"},
        {"kanji":"険悪","reading":"けんあく","type":"na","eng":"hostile"},
        {"kanji":"誠実","reading":"せいじつ","type":"na","eng":"sincere"},
        {"kanji":"正直","reading":"しょうじき","type":"na","eng":"honest"},
        {"kanji":"素直","reading":"すなお","type":"na","eng":"docile, honest"},
        {"kanji":"健康","reading":"けんこう","type":"na","eng":"healthy"},
        {"kanji":"不健康","reading":"ふけんこう","type":"na","eng":"unhealthy"},
        {"kanji":"清潔","reading":"せいけつ","type":"na","eng":"clean, hygienic"},
        {"kanji":"不潔","reading":"ふけつ","type":"na","eng":"unhygienic"},
        {"kanji":"謙虚","reading":"けんきょ","type":"na","eng":"humble"},
        {"kanji":"頑固","reading":"がんこ","type":"na","eng":"stubborn"},
        {"kanji":"我儘","reading":"わがまま","type":"na","eng":"selfish"},
        {"kanji":"勝手","reading":"かって","type":"na","eng":"selfish, one's own way"},
        {"kanji":"適当","reading":"てきとう","type":"na","eng":"random, appropriate"},
        {"kanji":"真面目","reading":"まじめ","type":"na","eng":"serious, diligent"},
        {"kanji":"気楽","reading":"きらく","type":"na","eng":"carefree"},
        {"kanji":"退屈","reading":"たいくつ","type":"na","eng":"boring"},
        {"kanji":"平気","reading":"へいき","type":"na","eng":"fine, unconcerned"},
        {"kanji":"平和","reading":"へいわ","type":"na","eng":"peaceful"},
        {"kanji":"必死","reading":"ひっし","type":"na","eng":"desperate"},
        {"kanji":"懸命","reading":"けんめい","type":"na","eng":"eager, strenuous"},
        {"kanji":"熱心","reading":"ねっしん","type":"na","eng":"enthusiastic"},
        {"kanji":"夢中","reading":"むちゅう","type":"na","eng":"absorbed, obsessed"},
        {"kanji":"不得意","reading":"ふとくい","type":"na","eng":"one's weak point"},
        {"kanji":"満足","reading":"まんぞく","type":"na","eng":"satisfied"},
        {"kanji":"不満","reading":"ふまん","type":"na","eng":"dissatisfied"},
        {"kanji":"幸運","reading":"こううん","type":"na","eng":"lucky"},
        {"kanji":"不運","reading":"ふうん","type":"na","eng":"unlucky"},
        {"kanji":"邪魔","reading":"じゃま","type":"na","eng":"hindrance, nuisance"},
        {"kanji":"下等","reading":"かとう","type":"na","eng":"inferior"},
        {"kanji":"上等","reading":"じょうとう","type":"na","eng":"superior, first-class"},
        {"kanji":"貧乏","reading":"びんぼう","type":"na","eng":"poor"},
        {"kanji":"贅沢","reading":"ぜいたく","type":"na","eng":"luxurious"},
        {"kanji":"派手","reading":"はで","type":"na","eng":"flashy"},
        {"kanji":"地味","reading":"じみ","type":"na","eng":"plain, sober"},
        {"kanji":"粋","reading":"いき","type":"na","eng":"chic, stylish"},
        {"kanji":"無愛想","reading":"ぶあいそう","type":"na","eng":"unsociable, blunt"},
        {"kanji":"器用","reading":"きよう","type":"na","eng":"skillful, handy"},
        {"kanji":"不器用","reading":"ぶきよう","type":"na","eng":"clumsy"},
        {"kanji":"乱暴","reading":"らんぼう","type":"na","eng":"violent, rough"},
        {"kanji":"利口","reading":"りこう","type":"na","eng":"clever, smart"},
        {"kanji":"馬鹿","reading":"ばか","type":"na","eng":"foolish, stupid"},
        {"kanji":"無名","reading":"むめい","type":"na","eng":"unknown"},
        {"kanji":"見事","reading":"みごと","type":"na","eng":"splendid, great"},
        {"kanji":"身軽","reading":"みがる","type":"na","eng":"agile, light"},
        {"kanji":"残酷","reading":"ざんこく","type":"na","eng":"cruel"},
        {"kanji":"冷淡","reading":"れいたん","type":"na","eng":"indifferent, cold"},
        {"kanji":"公平","reading":"こうへい","type":"na","eng":"fair"},
        {"kanji":"不公平","reading":"ふこうへい","type":"na","eng":"unfair"},
        {"kanji":"透明","reading":"とうめい","type":"na","eng":"transparent"},
        {"kanji":"新鮮","reading":"しんせん","type":"na","eng":"fresh"},
        {"kanji":"詳細","reading":"しょうさい","type":"na","eng":"detailed"},
        {"kanji":"巨大","reading":"きょだい","type":"na","eng":"huge, gigantic"},
        {"kanji":"卑劣","reading":"ひれつ","type":"na","eng":"mean, despicable"},
        {"kanji":"優雅","reading":"ゆうが","type":"na","eng":"elegant"},
        {"kanji":"気軽","reading":"きがる","type":"na","eng":"lighthearted"},
        {"kanji":"窮屈","reading":"きゅうくつ","type":"na","eng":"tight, cramped"},
        {"kanji":"迅速","reading":"じんそく","type":"na","eng":"quick, prompt"},
        {"kanji":"強引","reading":"ごういん","type":"na","eng":"pushy, forced"},
        {"kanji":"優秀","reading":"ゆうしゅう","type":"na","eng":"excellent"},
        {"kanji":"華やか","reading":"はなやか","type":"na","eng":"showy, brilliant"},
        {"kanji":"密接","reading":"みっせつ","type":"na","eng":"close, intimate"}
    ]
}